import { BadRequestException, ForbiddenException, Inject, Injectable, NotFoundException, OnModuleDestroy, OnModuleInit, UnauthorizedException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import type { AuthenticatedUser } from '../auth/types/auth-user.type';
import { MEMBER_REPOSITORY, type IMemberRepository } from '../persistence/interfaces/member-repository.interface';
import { SOMA_REPOSITORY, type ISomaRepository } from '../persistence/interfaces/soma-repository.interface';
import { NotificationsService } from '../notifications/notifications.service';
import { MercadoPagoQueueService } from './mercado-pago-queue.service';
import { ReceiptService } from './receipt.service';
import type { CheckoutInput, CheckoutResult, Contribution, FinancialReport, MercadoPagoPaymentRecord, MercadoPagoWebhookBody, SomaSettings, SubscriptionSummary } from './soma.types';

type WebhookInput={body:MercadoPagoWebhookBody;signature?:string;requestId?:string;queryDataId?:string;queryType?:string;headers?:Record<string,string|string[]|undefined>;ip?:string};
type Member={id:string;nome:string;email:string;ministerio?:string;ministerio_id?:string;celula?:string;celula_id?:string};
type MercadoPagoPayment={
 id?:number|string;status?:string;status_detail?:string;transaction_amount?:number;currency_id?:string;payment_method_id?:string;payment_type_id?:string;description?:string;external_reference?:string|null;
 date_created?:string;date_approved?:string|null;date_last_updated?:string;live_mode?:boolean;authorization_code?:string;transaction_details?:{net_received_amount?:number;total_paid_amount?:number;installment_amount?:number;transaction_id?:string};
 fee_details?:Array<{amount?:number;type?:string}>;payer?:{email?:string;first_name?:string;last_name?:string};installments?:number;
 card?:{last_four_digits?:string;first_six_digits?:string;cardholder?:{name?:string};issuer?:{id?:string;name?:string}};
 point_of_interaction?:{transaction_data?:{qr_code?:string;qr_code_base64?:string;ticket_url?:string}};date_of_expiration?:string;
};
type MercadoPagoPreference={id:string;init_point:string;sandbox_init_point:string;date_of_expiration?:string};

const ADMIN_ROLES=['ADMIN','DEVELOPER','MISSION_LEADER','MINISTRY_LEADER'];
const nowIso=()=>new Date().toISOString();
const number=(value:unknown)=>Number(value||0);
const text=(value:unknown)=>String(value??'');
const normalizeMonth=(value?:string)=>/^\d{4}-\d{2}$/.test(value||'')?value!:new Date().toISOString().slice(0,7);

@Injectable()
export class SomaService implements OnModuleInit,OnModuleDestroy {
 private timer?:NodeJS.Timeout;
 private contributions:Contribution[]=[];
 constructor(
  private readonly config:ConfigService,
  @Inject(SOMA_REPOSITORY) private readonly sheets:ISomaRepository,
  @Inject(MEMBER_REPOSITORY) private readonly members:IMemberRepository,
  private readonly notifications:NotificationsService,
  private readonly queue:MercadoPagoQueueService,
  private readonly receipts:ReceiptService,
 ){}
 onModuleInit(){if(!this.sheets.isDemo())this.timer=setInterval(()=>void this.reconcilePreviousDay(),24*60*60*1000)}
 onModuleDestroy(){if(this.timer)clearInterval(this.timer)}
 private defaults():SomaSettings{return{campaignName:'Soma+ Missão Brasília',description:'Sua contribuição sustenta a evangelização, formações e ações missionárias.',pixKey:text(this.config.get('SOMA_PIX_KEY')||'colodedeusfinanceirobsb@gmail.com'),pixKeyType:text(this.config.get('SOMA_PIX_KEY_TYPE')||'E-mail'),beneficiary:text(this.config.get('SOMA_BENEFICIARY')||'Colo de Deus - Missão Brasília'),city:text(this.config.get('SOMA_CITY')||'Brasília'),goal:number(this.config.get('SOMA_MONTHLY_GOAL')||50000),startDate:'2026-07-01',endDate:'2026-12-31',active:true,pixBank:text(this.config.get('SOMA_PIX_BANK')||'Mercado Pago'),pixAgency:text(this.config.get('SOMA_PIX_AGENCY')||'0001'),pixAccount:text(this.config.get('SOMA_PIX_ACCOUNT')||'8838451371-7'),pixCnpj:text(this.config.get('SOMA_PIX_CNPJ')||'66.312.954/0001-48'),subscriptionUrl:text(this.config.get('SOMA_SUBSCRIPTION_URL')||'https://mpago.la/1J1bojR'),pixQrCodeUrl:text(this.config.get('SOMA_PIX_QR_CODE_URL')||'/assets/mercado-pago-pix-qr.png')}}
 async settings():Promise<SomaSettings>{const base=this.defaults();try{const rows=await this.sheets.read('Financeiro');const row=rows.find(x=>(x.id||'principal')==='principal')||rows[0];if(!row)return base;return{...base,pixKey:row.pix_key||base.pixKey,pixBank:row.pix_bank||base.pixBank,pixAgency:row.pix_agency||base.pixAgency,pixAccount:row.pix_account||base.pixAccount,pixCnpj:row.pix_cnpj||base.pixCnpj,subscriptionUrl:row.subscription_url||base.subscriptionUrl,pixQrCodeUrl:row.pix_qrcode_drive||base.pixQrCodeUrl}}catch{return base}}
 async updateSettings(input:Record<string,unknown>,user:AuthenticatedUser){if(!['ADMIN','DEVELOPER','MISSION_LEADER'].includes(user.profile))throw new ForbiddenException('Apenas administradores podem alterar as configurações financeiras.');const current=await this.settings();const next={...current,...input,updated_at:nowIso()};const record={id:'principal',pix_key:text(next.pixKey),pix_bank:text(next.pixBank),pix_agency:text(next.pixAgency),pix_account:text(next.pixAccount),pix_cnpj:text(next.pixCnpj),subscription_url:text(next.subscriptionUrl),pix_qrcode_drive:text(next.pixQrCodeUrl),updated_at:text(next.updated_at)};if(!this.sheets.isDemo()){const rows=await this.sheets.read('Financeiro');if(rows.some(x=>x.id==='principal'))await this.sheets.updateRecord('Financeiro','id','principal',record);else await this.sheets.appendRecord('Financeiro',record)}return next}
 async subscription(user:AuthenticatedUser):Promise<SubscriptionSummary>{const settings=await this.settings();const payments=await this.listMyPayments(user);const latest=payments.find(x=>x.status==='approved');return{status:latest?'ACTIVE':'INACTIVE',plan:'Contribuição mensal',amount:latest?.amount??null,nextCharge:null,cardLastFour:latest?.card_last_four||null,manageUrl:settings.subscriptionUrl}}
 async list(user:AuthenticatedUser){return user.profile==='MEMBER'?this.contributions.filter(x=>x.email.toLowerCase()===user.email.toLowerCase()):this.contributions}
 create(input:Partial<Contribution>){const item:Contribution={id:randomUUID(),memberId:text(input.memberId),memberName:text(input.memberName),email:text(input.email),amount:number(input.amount),date:text(input.date||new Date().toISOString().slice(0,10)),referenceMonth:text(input.referenceMonth||new Date().toISOString().slice(0,7)),method:text(input.method||'PIX'),status:'PENDING',receiptUrl:text(input.receiptUrl),notes:text(input.notes)};this.contributions.unshift(item);return item}

 async createCheckout(input:CheckoutInput,user:AuthenticatedUser):Promise<CheckoutResult>{
  const member=await this.resolveCheckoutMember(input,user);const amount=Number(input.amount);if(!Number.isFinite(amount)||amount<1)throw new BadRequestException('Informe um valor válido, a partir de R$ 1,00.');
  const competence=normalizeMonth(input.competence);const externalReference=`SOMA|${member.id}|${competence}`;const apiUrl=text(this.config.get('PUBLIC_API_URL')||this.config.get('APP_API_URL')).replace(/\/$/,'');
  const frontendUrl=text(this.config.get('FRONTEND_URL')||this.config.get('WEB_URL')).replace(/\/$/,'');const expiration=new Date(Date.now()+30*60*1000).toISOString();
  const preference=await this.mpRequest<MercadoPagoPreference>('/checkout/preferences',{method:'POST',body:JSON.stringify({items:[{id:`soma-${competence}`,title:input.description||'Contribuição Soma+',description:`Contribuição de ${member.nome} - competência ${competence}`,quantity:1,currency_id:'BRL',unit_price:amount}],payer:{name:member.nome,email:member.email},external_reference:externalReference,notification_url:apiUrl?`${apiUrl}/api/soma/webhooks/mercadopago`:undefined,date_of_expiration:expiration,expires:true,back_urls:frontendUrl?{success:`${frontendUrl}/soma?payment=success`,pending:`${frontendUrl}/soma?payment=pending`,failure:`${frontendUrl}/soma?payment=failure`}:undefined,auto_return:frontendUrl?'approved':undefined,metadata:{member_id:member.id,competence}})},{'X-Idempotency-Key':randomUUID()});
  await this.audit('CHECKOUT_CREATED',externalReference,{member_id:member.id,amount:String(amount),preference_id:preference.id});
  return{preferenceId:preference.id,externalReference,checkoutUrl:preference.init_point,sandboxUrl:preference.sandbox_init_point,expiresAt:preference.date_of_expiration||expiration,status:'created'};
 }
 private async resolveCheckoutMember(input:CheckoutInput,user:AuthenticatedUser):Promise<Member>{
  const requested=input.memberId||user.memberId||user.id;const rows=await this.members.read('Membros');let row=rows.find(x=>x.id===requested);
  if(!row&&input.email)row=rows.find(x=>text(x.email).toLowerCase()===input.email!.toLowerCase());
  if(!row&&user.email)row=rows.find(x=>text(x.email).toLowerCase()===user.email.toLowerCase());
  if(!row)throw new NotFoundException('Membro não encontrado para criar o checkout.');
  if(user.profile==='MEMBER'&&row.id!==(user.memberId||user.id))throw new ForbiddenException('Um membro só pode criar checkout para o próprio cadastro.');
  return{id:text(row.id),nome:text(row.nome||input.name||user.name),email:text(row.email||input.email||user.email),ministerio:text(row.ministerio),ministerio_id:text(row.ministerio_id),celula:text(row.celula),celula_id:text(row.celula_id)};
 }

 async listMyPayments(user:AuthenticatedUser){const rows=await this.paymentRows();return rows.filter(x=>x.member_id===(user.memberId||user.id)||x.payer_email.toLowerCase()===user.email.toLowerCase()).sort((a,b)=>(b.date_approved||b.date_created).localeCompare(a.date_approved||a.date_created))}
 async paymentReport(user:AuthenticatedUser,month=normalizeMonth()){const report=await this.financialReport(user,{from:`${month}-01`,to:`${month}-31`});return{month,scope:ADMIN_ROLES.includes(user.profile)?'ADMIN':'MEMBER',total:report.totals.gross,approved:report.counters.approved,pending:report.counters.pending,rejected:report.counters.rejected,payments:report.payments}}
 async financialReport(user:AuthenticatedUser,filter:{from?:string;to?:string;status?:string;method?:string}={}):Promise<FinancialReport>{
  let rows=await this.paymentRows();if(!ADMIN_ROLES.includes(user.profile))rows=rows.filter(x=>x.member_id===(user.memberId||user.id)||x.payer_email.toLowerCase()===user.email.toLowerCase());
  const from=filter.from||`${new Date().getFullYear()}-01-01`,to=filter.to||`${new Date().getFullYear()}-12-31`;
  rows=rows.filter(x=>{const d=(x.date_approved||x.date_created).slice(0,10);return d>=from&&d<=to&&(!filter.status||x.status===filter.status)&&(!filter.method||x.payment_type===filter.method||x.payment_method===filter.method)});
  const approved=rows.filter(x=>x.status==='approved');const sum=(list:MercadoPagoPaymentRecord[],key:'amount'|'fee_amount'|'net_amount')=>list.reduce((s,x)=>s+number(x[key]),0);const today=new Date().toISOString().slice(0,10);const weekAgo=new Date(Date.now()-6*86400000).toISOString().slice(0,10);const month=today.slice(0,7),year=today.slice(0,4);
  const periodGross=(predicate:(x:MercadoPagoPaymentRecord)=>boolean)=>sum(approved.filter(predicate),'amount');
  const group=(key:(x:MercadoPagoPaymentRecord)=>string)=>Object.values(approved.reduce<Record<string,{key:string;label:string;count:number;gross:number;net:number}>>((acc,x)=>{const k=key(x)||'outros';const item=acc[k]||{key:k,label:k,count:0,gross:0,net:0};item.count++;item.gross+=x.amount;item.net+=x.net_amount;acc[k]=item;return acc},{}));
  const members=await this.memberRows();const byOrg=(kind:'ministry'|'cell')=>{const buckets=new Map<string,{id:string;name:string;members:Member[]}>();for(const m of members){const id=kind==='ministry'?(m.ministerio_id||m.ministerio||'sem-ministerio'):(m.celula_id||m.celula||'sem-celula');const name=kind==='ministry'?(m.ministerio||'Sem ministério'):(m.celula||'Sem célula');const b=buckets.get(id)||{id,name,members:[]};b.members.push(m);buckets.set(id,b)}return [...buckets.values()].map(b=>{const ids=new Set(b.members.map(m=>m.id));const pays=approved.filter(p=>ids.has(p.member_id));const payers=new Set(pays.map(p=>p.member_id));return{id:b.id,name:b.name,members:b.members.length,payers:payers.size,pending:Math.max(0,b.members.length-payers.size),gross:sum(pays,'amount'),percentage:b.members.length?Math.round(payers.size/b.members.length*100):0}}).sort((a,b)=>b.gross-a.gross)};
  const byMonth=group(x=>x.reference_month).map(x=>({month:x.key,gross:x.gross,fees:sum(approved.filter(p=>p.reference_month===x.key),'fee_amount'),net:x.net,count:x.count})).sort((a,b)=>a.month.localeCompare(b.month));
  return{period:{from,to},totals:{gross:sum(approved,'amount'),fees:sum(approved,'fee_amount'),net:sum(approved,'net_amount'),ticketAverage:approved.length?sum(approved,'amount')/approved.length:0,today:periodGross(x=>(x.date_approved||x.date_created).startsWith(today)),week:periodGross(x=>(x.date_approved||x.date_created).slice(0,10)>=weekAgo),month:periodGross(x=>(x.date_approved||x.date_created).startsWith(month)),year:periodGross(x=>(x.date_approved||x.date_created).startsWith(year))},counters:{approved:approved.length,pending:rows.filter(x=>['pending','in_process','authorized'].includes(x.status)).length,rejected:rows.filter(x=>['rejected','cancelled'].includes(x.status)).length,refunded:rows.filter(x=>x.status.includes('refund')).length,chargedBack:rows.filter(x=>x.status==='charged_back').length},byMethod:group(x=>x.payment_type||x.payment_method),byMonth,byMinistry:byOrg('ministry'),byCell:byOrg('cell'),payments:rows};
 }
 async summary(month=normalizeMonth()){const report=await this.financialReport({profile:'ADMIN'} as AuthenticatedUser,{from:`${month}-01`,to:`${month}-31`});const goal=(await this.settings()).goal;return{month,total:report.totals.gross,goal,percentage:goal?Math.min(100,Math.round(report.totals.gross/goal*100)):0,confirmed:report.counters.approved,pending:report.counters.pending,average:report.totals.ticketAverage}}

 receiveMercadoPagoWebhook(input:WebhookInput){
  const dataId=text(input.queryDataId||input.body.data?.id).trim();const type=text(input.queryType||input.body.type).trim();if(!dataId)return{received:true,queued:false,reason:'Notificação sem data.id.'};
  this.validateWebhookSignature(dataId,input.signature,input.requestId);const action=input.body.action||`${type||'unknown'}.updated`;const key=`${dataId}|${action}|${input.body.date_created||''}`;
  const queued=this.queue.enqueue(key,()=>this.processWebhook({...input,queryDataId:dataId,queryType:type}));return{received:true,queued,id:dataId,type,queueSize:this.queue.size()};
 }
 private async processWebhook(input:WebhookInput){const started=Date.now();const dataId=text(input.queryDataId);const type=text(input.queryType||input.body.type);const action=input.body.action||`${type||'unknown'}.updated`;let status='PROCESSED',error='';try{if(type==='payment'||action.startsWith('payment.')){const payment=await this.fetchPayment(dataId);await this.savePayment(payment,action);status='PAYMENT_SAVED'}else status='IGNORED'}catch(e){status='ERROR';error=e instanceof Error?e.message:String(e);throw e}finally{await this.saveWebhookLog({resourceId:dataId,type:type||'unknown',action,status,error,input,processingTime:Date.now()-started})}}
 private validateWebhookSignature(dataId:string,signature?:string,requestId?:string){const secret=text(this.config.get('MERCADO_PAGO_WEBHOOK_SECRET')).trim();const allowUnsigned=text(this.config.get('MERCADO_PAGO_ALLOW_UNSIGNED_WEBHOOKS')).toLowerCase()==='true';if(!secret){if(allowUnsigned)return;throw new UnauthorizedException('MERCADO_PAGO_WEBHOOK_SECRET não configurado.')}if(!signature||!requestId)throw new UnauthorizedException('Assinatura do webhook ausente.');const parts=Object.fromEntries(signature.split(',').map(p=>p.trim().split('=')));const ts=parts.ts,received=parts.v1;if(!ts||!received)throw new UnauthorizedException('Assinatura inválida.');const expected=createHmac('sha256',secret).update(`id:${dataId.toLowerCase()};request-id:${requestId};ts:${ts};`).digest('hex');const a=Buffer.from(expected),b=Buffer.from(received);if(a.length!==b.length||!timingSafeEqual(a,b))throw new UnauthorizedException('Origem do webhook não autenticada.')}
 private fetchPayment(id:string){return this.mpRequest<MercadoPagoPayment>(`/v1/payments/${encodeURIComponent(id)}`)}
 private async savePayment(payment:MercadoPagoPayment,action:string){
  const paymentId=text(payment.id);const external=text(payment.external_reference);const parsed=this.parseExternalReference(external);const email=text(payment.payer?.email).trim().toLowerCase();const member=parsed.memberId?await this.findMemberById(parsed.memberId):await this.findMemberByEmail(email);const created=text(payment.date_created||nowIso());const approved=text(payment.date_approved);const fees=(payment.fee_details||[]).reduce((s,x)=>s+number(x.amount),0);const net=number(payment.transaction_details?.net_received_amount)||Math.max(0,number(payment.transaction_amount)-fees);const hash=this.receipts.hash({payment_id:paymentId,member_id:member?.id||parsed.memberId,amount:number(payment.transaction_amount),date_approved:approved});
  const old=(await this.paymentRows()).find(x=>x.payment_id===paymentId);const record:MercadoPagoPaymentRecord={id:paymentId,payment_id:paymentId,member_id:member?.id||parsed.memberId,member_name:member?.nome||[payment.payer?.first_name,payment.payer?.last_name].filter(Boolean).join(' '),payer_email:email,external_reference:external,status:text(payment.status||'unknown'),status_detail:text(payment.status_detail),amount:number(payment.transaction_amount),total_paid_amount:number(payment.transaction_details?.total_paid_amount)||number(payment.transaction_amount),fee_amount:fees,net_amount:net,currency:text(payment.currency_id||'BRL'),payment_method:text(payment.payment_method_id),payment_type:text(payment.payment_type_id),description:text(payment.description||'Contribuição Soma+'),date_created:created,date_approved:approved,date_last_updated:text(payment.date_last_updated||nowIso()),reference_month:parsed.competence||(approved||created).slice(0,7),live_mode:text(Boolean(payment.live_mode)),webhook_action:action,updated_at:nowIso(),card_brand:text(payment.payment_method_id),card_issuer:text(payment.card?.issuer?.name||payment.card?.issuer?.id),card_last_four:text(payment.card?.last_four_digits),installments:number(payment.installments),installment_amount:number(payment.transaction_details?.installment_amount),authorization_code:text(payment.authorization_code),transaction_id:text(payment.transaction_details?.transaction_id||payment.id),nsu:text(payment.authorization_code),pix_qr_code:text(payment.point_of_interaction?.transaction_data?.qr_code),pix_qr_code_base64:text(payment.point_of_interaction?.transaction_data?.qr_code_base64),pix_ticket_url:text(payment.point_of_interaction?.transaction_data?.ticket_url),pix_expiration_date:text(payment.date_of_expiration),paid_in_seconds:approved&&created?Math.max(0,Math.round((Date.parse(approved)-Date.parse(created))/1000)):0,receipt_id:`REC-${paymentId}`,receipt_hash:hash};
  if(!this.sheets.isDemo()){if(old)await this.sheets.updateRecord('Pagamentos','id',paymentId,this.toRow(record));else await this.sheets.appendRecord('Pagamentos',this.toRow(record));await this.sheets.appendRecord('HistoricoPagamentos',{id:randomUUID(),payment_id:paymentId,member_id:record.member_id,previous_status:old?.status||'',status:record.status,status_detail:record.status_detail,action,occurred_at:nowIso(),payload:JSON.stringify({status:record.status,status_detail:record.status_detail})});await this.upsertMemberContribution(record)}
  if(!old||old.status!==record.status)await this.notifyPayment(record);await this.audit(`PAYMENT_${record.status.toUpperCase()}`,paymentId,{member_id:record.member_id,amount:String(record.amount),status:record.status});
 }
 private async upsertMemberContribution(record:MercadoPagoPaymentRecord){const rows=await this.sheets.read('ContribuicoesMembros');const id=`${record.member_id}|${record.reference_month}`;const payload={id,member_id:record.member_id,member_name:record.member_name,reference_month:record.reference_month,status:record.status,last_payment_id:record.payment_id,last_payment_at:record.date_approved||record.date_created,amount:String(record.amount),payment_method:record.payment_type||record.payment_method,card_last_four:record.card_last_four,receipt_id:record.receipt_id,updated_at:nowIso()};if(rows.some(x=>x.id===id))await this.sheets.updateRecord('ContribuicoesMembros','id',id,payload);else await this.sheets.appendRecord('ContribuicoesMembros',payload)}
 private async notifyPayment(record:MercadoPagoPaymentRecord){if(!record.member_id)return;const map:Record<string,{title:string;message:string}>={approved:{title:'Pagamento aprovado',message:`Sua contribuição de ${this.money(record.amount)} foi creditada com sucesso${record.card_last_four?` no cartão final ${record.card_last_four}`:''}.`},rejected:{title:'Pagamento recusado',message:`O Mercado Pago não aprovou a contribuição de ${this.money(record.amount)}. Consulte os detalhes e tente novamente.`},refunded:{title:'Pagamento estornado',message:`A contribuição de ${this.money(record.amount)} foi estornada.`},charged_back:{title:'Pagamento contestado',message:`A contribuição de ${this.money(record.amount)} recebeu uma contestação.`},in_process:{title:'Pagamento em análise',message:`Sua contribuição de ${this.money(record.amount)} está em análise.`},pending:{title:'Pagamento pendente',message:`Sua contribuição de ${this.money(record.amount)} aguarda confirmação.`}};const item=map[record.status];if(item)await this.notifications.createSystem({title:item.title,message:item.message,type:'SOMA',audience:'INDIVIDUAL',recipientIds:[record.member_id],origin:'Mercado Pago',referenceType:'PAGAMENTO',referenceId:record.payment_id,link:'/soma?tab=contribuicoes'})}
 private parseExternalReference(value:string){const match=value.match(/^SOMA\|([^|]+)\|(\d{4}-\d{2})$/);return{memberId:match?.[1]||'',competence:match?.[2]||''}}
 private async findMemberById(id:string){if(!id)return null;const row=(await this.memberRows()).find(x=>x.id===id);return row||null}
 private async findMemberByEmail(email:string){if(!email)return null;const row=(await this.memberRows()).find(x=>x.email.toLowerCase()===email.toLowerCase());return row||null}
 private async memberRows():Promise<Member[]>{try{return(await this.members.read('Membros')).map(x=>({id:text(x.id),nome:text(x.nome),email:text(x.email),ministerio:text(x.ministerio),ministerio_id:text(x.ministerio_id),celula:text(x.celula),celula_id:text(x.celula_id)}))}catch{return[]}}
 private async paymentRows(){try{return(await this.sheets.read('Pagamentos')).map(x=>this.rowToPayment(x))}catch{try{return(await this.sheets.read('PagamentosMercadoPago')).map(x=>this.rowToPayment(x))}catch{return[]}}}
 private rowToPayment(row:Record<string,string>):MercadoPagoPaymentRecord{return{id:text(row.id||row.payment_id),payment_id:text(row.payment_id||row.id),member_id:text(row.member_id),member_name:text(row.member_name),payer_email:text(row.payer_email),external_reference:text(row.external_reference),status:text(row.status),status_detail:text(row.status_detail),amount:number(row.amount),total_paid_amount:number(row.total_paid_amount||row.amount),fee_amount:number(row.fee_amount),net_amount:number(row.net_amount||row.amount),currency:text(row.currency||'BRL'),payment_method:text(row.payment_method),payment_type:text(row.payment_type),description:text(row.description),date_created:text(row.date_created),date_approved:text(row.date_approved),date_last_updated:text(row.date_last_updated),reference_month:text(row.reference_month),live_mode:text(row.live_mode),webhook_action:text(row.webhook_action),updated_at:text(row.updated_at),card_brand:text(row.card_brand),card_issuer:text(row.card_issuer),card_last_four:text(row.card_last_four),installments:number(row.installments),installment_amount:number(row.installment_amount),authorization_code:text(row.authorization_code),transaction_id:text(row.transaction_id),nsu:text(row.nsu),pix_qr_code:text(row.pix_qr_code),pix_qr_code_base64:text(row.pix_qr_code_base64),pix_ticket_url:text(row.pix_ticket_url),pix_expiration_date:text(row.pix_expiration_date),paid_in_seconds:number(row.paid_in_seconds),receipt_id:text(row.receipt_id),receipt_hash:text(row.receipt_hash)}}
 private toRow(record:MercadoPagoPaymentRecord){return Object.fromEntries(Object.entries(record).map(([k,v])=>[k,text(v)]))}
 private async saveWebhookLog(args:{resourceId:string;type:string;action:string;status:string;error:string;input:WebhookInput;processingTime:number}){if(this.sheets.isDemo())return;await this.sheets.appendRecord('WebhookLogs',{id:randomUUID(),resource_id:args.resourceId,type:args.type,action:args.action,received_at:nowIso(),request_id:text(args.input.requestId),signature:text(args.input.signature),ip:text(args.input.ip),processing_time_ms:String(args.processingTime),status:args.status,retry:'0',error:args.error,payload:JSON.stringify(args.input.body),headers:JSON.stringify(args.input.headers||{})})}
 private async audit(event:string,reference:string,data:Record<string,string>){if(this.sheets.isDemo())return;try{await this.sheets.appendRecord('AuditoriaFinanceira',{id:randomUUID(),event,reference,data:JSON.stringify(data),created_at:nowIso()})}catch{}}
 async receipt(paymentId:string,user:AuthenticatedUser){const payment=(await this.paymentRows()).find(x=>x.payment_id===paymentId);if(!payment)throw new NotFoundException('Pagamento não encontrado.');if(!ADMIN_ROLES.includes(user.profile)&&payment.member_id!==(user.memberId||user.id))throw new ForbiddenException('Recibo indisponível para este usuário.');const apiUrl=text(this.config.get('PUBLIC_API_URL')||'').replace(/\/$/,'');return this.receipts.pdf(payment,`${apiUrl}/api/soma/receipts/${payment.payment_id}/validate?hash=${payment.receipt_hash}`)}
 async validateReceipt(paymentId:string,hash:string){const payment=(await this.paymentRows()).find(x=>x.payment_id===paymentId);return{valid:!!payment&&payment.receipt_hash===hash&&payment.status==='approved',payment:payment?{paymentId:payment.payment_id,memberName:payment.member_name,amount:payment.amount,date:payment.date_approved,status:payment.status}:null}}
 async exportReport(user:AuthenticatedUser,format:'csv'|'xls',filter:{from?:string;to?:string}){const report=await this.financialReport(user,filter);const headers=['ID','Membro','E-mail','Status','Valor bruto','Taxas','Valor líquido','Forma','Cartão final','Parcelas','Data'];const lines=[headers,...report.payments.map(x=>[x.payment_id,x.member_name,x.payer_email,x.status,x.amount,x.fee_amount,x.net_amount,x.payment_type||x.payment_method,x.card_last_four,x.installments,x.date_approved||x.date_created])];const sep=format==='csv'?';':'\t';return Buffer.from('\ufeff'+lines.map(row=>row.map(v=>`"${text(v).replaceAll('"','""')}"`).join(sep)).join('\n'))}
 async reconcilePreviousDay(){const token=text(this.config.get('MERCADO_PAGO_ACCESS_TOKEN'));if(!token||this.sheets.isDemo())return{checked:0,updated:0};const end=new Date(),begin=new Date(Date.now()-24*60*60*1000);const query=new URLSearchParams({'range':'date_created','begin_date':begin.toISOString(),'end_date':end.toISOString(),'limit':'100'});const result=await this.mpRequest<{results?:MercadoPagoPayment[]}>(`/v1/payments/search?${query}`);let updated=0;for(const payment of result.results||[]){await this.savePayment(payment,'reconciliation.daily');updated++}await this.sheets.appendRecord('FinanceiroMensal',{id:nowIso(),month:new Date().toISOString().slice(0,7),checked:String(result.results?.length||0),updated:String(updated),executed_at:nowIso()});return{checked:result.results?.length||0,updated}}
 private async mpRequest<T>(path:string,init:RequestInit={},{...extraHeaders}:Record<string,string>={}){const token=text(this.config.get('MERCADO_PAGO_ACCESS_TOKEN')).trim();if(!token)throw new UnauthorizedException('MERCADO_PAGO_ACCESS_TOKEN não configurado.');const response=await fetch(`https://api.mercadopago.com${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...extraHeaders,...(init.headers||{})}});if(!response.ok)throw new BadRequestException(`Mercado Pago retornou HTTP ${response.status}: ${(await response.text()).slice(0,500)}`);return await response.json() as T}
 private money(value:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value)}
}
