import { AccessTimeOutlined, GroupsOutlined, LocationOnOutlined, PersonOutlined } from '@mui/icons-material';
import { Avatar, AvatarGroup, Box, Button, Card, Chip, Stack, Typography } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import type { Community } from '../../types/community';
export function CommunityCard({community}:{community:Community}){const nav=useNavigate();const schedule=community.type==='CELL'?`${community.weekday||'Dia não definido'} • ${community.time||'Sem horário'}`:`${community.startDate||'Data não definida'} ${community.time||''} até ${community.endDate||community.startDate||''} ${community.endTime||''}`;const statusLabel=community.status==='FINISHED'?'Encerrado':community.status==='CANCELLED'?'Cancelado':'Próximo';return <Card sx={{p:2.5,height:'100%',display:'flex',flexDirection:'column'}}>
 <Stack direction="row" justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1}><Chip size="small" color="primary" variant="outlined" label={community.type==='CELL'?'Célula':'Cenáculo'}/>{community.type==='CENACLE'&&<Chip size="small" color={community.status==='CANCELLED'?'error':community.status==='FINISHED'?'default':'success'} label={statusLabel}/>}</Stack><Typography variant="h6" mt={1}>{community.name}</Typography></Box><GroupsOutlined color="primary"/></Stack>
 <Typography color="text.secondary" fontSize={13} mt={1.2} flex={1}>{community.description||'Sem descrição cadastrada.'}</Typography>
 <Stack spacing={1} mt={2} color="text.secondary"><Stack direction="row" gap={1}><PersonOutlined fontSize="small"/><Typography fontSize={13}>{community.leader.name}</Typography></Stack><Stack direction="row" gap={1}><AccessTimeOutlined fontSize="small"/><Typography fontSize={13}>{schedule}</Typography></Stack><Stack direction="row" gap={1}><LocationOnOutlined fontSize="small"/><Typography fontSize={13}>{community.neighborhood||community.city||'Local não informado'}</Typography></Stack></Stack>
 <Stack direction="row" justifyContent="space-between" alignItems="center" mt={2}><AvatarGroup max={4}>{community.participants.map(p=><Avatar key={p.id} src={p.photo} alt={p.name}/>)}</AvatarGroup><Typography color="text.secondary" fontSize={13}>{community.participants.length} participantes</Typography></Stack>
 <Button variant="outlined" fullWidth sx={{mt:2}} onClick={()=>nav(`/comunidades/${community.id}`)}>Ver detalhes</Button>
 </Card>}
