import { FilterAltOutlined, RefreshOutlined, SearchOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Card, Chip, CircularProgress, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { useCallback, useEffect, useState } from 'react';
import { api, apiErrorMessage } from '../services/api';

type AuditRow={id:string;action:string;module:string;entity:string;recordId:string;userId:string;userName:string;userEmail:string;profile:string;description:string;previousData:string;newData:string;ip:string;userAgent:string;createdAt:string};
const actions=['','LOGIN','LOGOUT','CREATE','UPDATE','DELETE','RESTORE','PERMISSION','CHANGE'];
const labels:Record<string,string>={LOGIN:'Login',LOGOUT:'Logout',CREATE:'Criação',UPDATE:'Edição',DELETE:'Exclusão',RESTORE:'Restauração',PERMISSION:'Permissões',CHANGE:'Alteração'};
export function AuditPage(){
 const [rows,setRows]=useState<AuditRow[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const[action,setAction]=useState('');const[module,setModule]=useState('');const[user,setUser]=useState('');const[q,setQ]=useState('');const[startDate,setStartDate]=useState('');const[endDate,setEndDate]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const params=new URLSearchParams();if(action)params.set('action',action);if(module)params.set('module',module);if(user)params.set('user',user);if(q)params.set('q',q);if(startDate)params.set('startDate',startDate);if(endDate)params.set('endDate',endDate);setRows((await api.get<AuditRow[]>(`/audit?${params}`)).data);}catch(e){setError(apiErrorMessage(e));}finally{setLoading(false);}},[action,module,user,q,startDate,endDate]);
 useEffect(()=>{void load();},[load]);
 const modules=[...new Set(rows.map(r=>r.module).filter(Boolean))].sort();
 return <Box><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Typography variant="h4">Auditoria</Typography><Typography color="text.secondary">Histórico de logins, alterações, permissões, exclusões e restaurações.</Typography></Box><Button startIcon={<RefreshOutlined/>} variant="outlined" onClick={()=>void load()}>Atualizar</Button></Stack>
 <Card sx={{p:2.5,mb:3}}><Stack direction="row" alignItems="center" gap={1} mb={2}><FilterAltOutlined color="primary"/><Typography variant="h6">Filtros</Typography></Stack><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:2}}><TextField select label="Ação" value={action} onChange={e=>setAction(e.target.value)}>{actions.map(v=><MenuItem key={v||'all'} value={v}>{v?labels[v]||v:'Todas'}</MenuItem>)}</TextField><TextField select label="Módulo" value={module} onChange={e=>setModule(e.target.value)}><MenuItem value="">Todos</MenuItem>{modules.map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</TextField><TextField label="Usuário" value={user} onChange={e=>setUser(e.target.value)} placeholder="Nome, e-mail ou ID"/><TextField type="date" label="Data inicial" InputLabelProps={{shrink:true}} value={startDate} onChange={e=>setStartDate(e.target.value)}/><TextField type="date" label="Data final" InputLabelProps={{shrink:true}} value={endDate} onChange={e=>setEndDate(e.target.value)}/><TextField label="Pesquisar" value={q} onChange={e=>setQ(e.target.value)} InputProps={{startAdornment:<SearchOutlined sx={{mr:1}}/>}}/></Box></Card>
 {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{loading?<Box textAlign="center" py={8}><CircularProgress/></Box>:<Stack gap={1.5}>{rows.length===0&&<Alert severity="info">Nenhum registro encontrado.</Alert>}{rows.map(r=><Card key={r.id} sx={{p:2.25}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={1}><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Chip size="small" color={r.action==='DELETE'?'error':r.action==='RESTORE'?'success':r.action==='PERMISSION'?'warning':'default'} label={labels[r.action]||r.action}/><Chip size="small" variant="outlined" label={r.module}/><Typography fontWeight={600}>{r.userName||r.userEmail||'Sistema'}</Typography></Stack><Typography variant="body2" color="text.secondary">{new Date(r.createdAt).toLocaleString('pt-BR')}</Typography></Stack><Typography mt={1}>{r.description}</Typography><Stack direction={{xs:'column',sm:'row'}} gap={2} mt={1}><Typography variant="caption" color="text.secondary">E-mail: {r.userEmail||'—'}</Typography><Typography variant="caption" color="text.secondary">Registro: {r.recordId||'—'}</Typography><Typography variant="caption" color="text.secondary">IP: {r.ip||'—'}</Typography></Stack>{r.newData&&<Box component="pre" sx={{mt:1.5,p:1.5,bgcolor:'background.default',borderRadius:1,overflow:'auto',fontSize:12,whiteSpace:'pre-wrap'}}>{r.newData}</Box>}</Card>)}</Stack>}</Box>;
}
