import { AccountBalanceWalletOutlined, DownloadOutlined, PaidOutlined, PixOutlined, ReceiptLongOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, TextField, Typography } from '@mui/material';
import { useEffect, useMemo, useState } from 'react';
import { useAuth } from '../auth/AuthContext';
import { api, apiErrorMessage } from '../services/api';

type Payment={payment_id:string;member_name:string;status:string;amount:number;fee_amount:number;net_amount:number;payment_method:string;payment_type:string;card_brand:string;card_last_four:string;installments:number;installment_amount:number;date_created:string;date_approved:string;pix_ticket_url:string;pix_expiration_date:string};
type Report={totals:{gross:number;fees:number;net:number;ticketAverage:number;today:number;week:number;month:number;year:number};counters:{approved:number;pending:number;rejected:number;refunded:number;chargedBack:number};byMethod:Array<{key:string;count:number;gross:number}>;byMonth:Array<{month:string;gross:number;net:number;count:number}>;byMinistry:Array<{id:string;name:string;members:number;payers:number;pending:number;gross:number;percentage:number}>;byCell:Array<{id:string;name:string;members:number;payers:number;pending:number;gross:number;percentage:number}>;payments:Payment[]};
const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value||0);
const statusLabel=(value:string)=>({approved:'Aprovado',pending:'Pendente',in_process:'Em análise',rejected:'Recusado',cancelled:'Cancelado',refunded:'Estornado',charged_back:'Contestado'}[value]||value);

export function FinancialEnterprisePanel({admin=false}:{admin?:boolean}){
 const {user}=useAuth();const [report,setReport]=useState<Report|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [checkoutOpen,setCheckoutOpen]=useState(false);const [amount,setAmount]=useState('');const [competence,setCompetence]=useState(new Date().toISOString().slice(0,7));const [creating,setCreating]=useState(false);const [status,setStatus]=useState('');const [method,setMethod]=useState('');
 const from=useMemo(()=>`${new Date().getFullYear()}-01-01`,[]);const to=useMemo(()=>`${new Date().getFullYear()}-12-31`,[]);
 const load=()=>{setLoading(true);setError('');api.get<Report>(admin?'/soma/financial/report':'/soma/financial/my-report',{params:{from,to,status:status||undefined,method:method||undefined}}).then(r=>setReport(r.data)).catch(e=>setError(apiErrorMessage(e))).finally(()=>setLoading(false))};
 useEffect(()=>{load()},[status,method]);
 const checkout=async()=>{setCreating(true);setError('');try{const {data}=await api.post<{checkoutUrl:string;sandboxUrl:string}>('/soma/checkout',{memberId:user?.memberId,name:user?.name,email:user?.email,amount:Number(amount),competence});window.location.href=data.checkoutUrl||data.sandboxUrl}catch(e){setError(apiErrorMessage(e));setCreating(false)}};
 const download=(format:'csv'|'xls')=>{const url=`${api.defaults.baseURL}/soma/financial/export/${format}?from=${from}&to=${to}`;window.open(url,'_blank')};
 if(loading&&!report)return <Box minHeight={320} display="grid" sx={{placeItems:'center'}}><CircularProgress/></Box>;
 return <Stack spacing={2}>
  {error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}
  <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h5" fontWeight={900}>{admin?'Centro Financeiro':'Minhas Contribuições'}</Typography><Typography color="text.secondary">Pagamentos vinculados ao seu cadastro pelo identificador individual do checkout.</Typography></Box><Button variant="contained" startIcon={<PaidOutlined/>} onClick={()=>setCheckoutOpen(true)}>Nova contribuição</Button></Stack>
  {report&&<><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',lg:'repeat(4,1fr)'},gap:2}}>{[
   ['Hoje',report.totals.today],['Semana',report.totals.week],['Mês',report.totals.month],['Ano',report.totals.year],['Taxas',report.totals.fees],['Líquido',report.totals.net],['Ticket médio',report.totals.ticketAverage],['Aprovados',report.counters.approved]
  ].map(([label,value])=><Card key={String(label)}><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h6" fontWeight={900}>{typeof value==='number'&&label!=='Aprovados'?money(value):value}</Typography></CardContent></Card>)}</Box>
  {admin&&<Stack direction={{xs:'column',sm:'row'}} gap={1}><TextField select size="small" label="Status" value={status} onChange={e=>setStatus(e.target.value)} sx={{minWidth:170}}><MenuItem value="">Todos</MenuItem><MenuItem value="approved">Aprovados</MenuItem><MenuItem value="pending">Pendentes</MenuItem><MenuItem value="rejected">Recusados</MenuItem></TextField><TextField select size="small" label="Forma" value={method} onChange={e=>setMethod(e.target.value)} sx={{minWidth:170}}><MenuItem value="">Todas</MenuItem><MenuItem value="pix">PIX</MenuItem><MenuItem value="credit_card">Cartão</MenuItem><MenuItem value="ticket">Boleto</MenuItem></TextField><Button startIcon={<DownloadOutlined/>} onClick={()=>download('xls')}>Excel</Button><Button startIcon={<DownloadOutlined/>} onClick={()=>download('csv')}>CSV</Button></Stack>}
  <Card><CardContent><Typography variant="h6" fontWeight={900} mb={2}>Histórico financeiro</Typography><Box sx={{overflowX:'auto'}}><Box component="table" sx={{width:'100%',borderCollapse:'collapse','th,td':{p:1.2,borderBottom:'1px solid',borderColor:'divider',textAlign:'left',whiteSpace:'nowrap'}}}><thead><tr><th>Data</th>{admin&&<th>Membro</th>}<th>Valor</th><th>Forma</th><th>Cartão/PIX</th><th>Status</th><th>Recibo</th></tr></thead><tbody>{report.payments.map(p=><tr key={p.payment_id}><td>{new Date(p.date_approved||p.date_created).toLocaleDateString('pt-BR')}</td>{admin&&<td>{p.member_name}</td>}<td>{money(p.amount)}</td><td>{p.payment_type||p.payment_method}</td><td>{p.card_last_four?`${p.card_brand||'Cartão'} •••• ${p.card_last_four}${p.installments>1?` · ${p.installments}x`:''}`:p.payment_type==='bank_transfer'?<Chip size="small" icon={<PixOutlined/>} label="PIX"/>:'—'}</td><td><Chip size="small" color={p.status==='approved'?'success':p.status==='rejected'?'error':'warning'} label={statusLabel(p.status)}/></td><td><Button size="small" startIcon={<ReceiptLongOutlined/>} href={`${api.defaults.baseURL}/soma/receipts/${p.payment_id}`} target="_blank" disabled={p.status!=='approved'}>PDF</Button></td></tr>)}</tbody></Box></Box></CardContent></Card>
  {admin&&<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1fr 1fr'},gap:2}}><OrgCard title="Por ministério" items={report.byMinistry}/><OrgCard title="Por célula" items={report.byCell}/></Box>}</>}
  <Dialog open={checkoutOpen} onClose={()=>!creating&&setCheckoutOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Checkout Mercado Pago</DialogTitle><DialogContent><Stack spacing={2} mt={1}><Alert severity="info">O pagamento será identificado por <strong>SOMA|MEMBRO|COMPETÊNCIA</strong>, mesmo que o cartão pertença a outra pessoa.</Alert><TextField label="Valor da contribuição" type="number" value={amount} onChange={e=>setAmount(e.target.value)} InputProps={{startAdornment:<AccountBalanceWalletOutlined sx={{mr:1}}/>}}/><TextField label="Competência" type="month" value={competence} onChange={e=>setCompetence(e.target.value)} InputLabelProps={{shrink:true}}/></Stack></DialogContent><DialogActions><Button onClick={()=>setCheckoutOpen(false)} disabled={creating}>Cancelar</Button><Button variant="contained" onClick={checkout} disabled={creating||Number(amount)<1}>{creating?'Criando...':'Ir para pagamento'}</Button></DialogActions></Dialog>
 </Stack>
}
function OrgCard({title,items}:{title:string;items:Array<{id:string;name:string;members:number;payers:number;pending:number;gross:number;percentage:number}>}){return <Card><CardContent><Typography variant="h6" fontWeight={900} mb={1}>{title}</Typography>{items.slice(0,8).map(item=><Stack key={item.id} direction="row" justifyContent="space-between" py={1} borderBottom="1px solid" borderColor="divider"><Box><Typography fontWeight={800}>{item.name}</Typography><Typography variant="caption" color="text.secondary">{item.payers} de {item.members} contribuintes · {item.pending} pendentes</Typography></Box><Box textAlign="right"><Typography fontWeight={900}>{money(item.gross)}</Typography><Typography variant="caption">{item.percentage}%</Typography></Box></Stack>)}</CardContent></Card>}
