import { AddOutlined, CloudOutlined, MapOutlined, SaveOutlined, SettingsSuggestOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, MenuItem, Stack, Switch, TextField, Typography } from '@mui/material';
import { useEffect, useState } from 'react';
import type { IntegrationStatus } from '../components/maps/types';
import { api, apiErrorMessage } from '../services/api';
import type { IntegrationConfigRecord } from '../types';

const empty: IntegrationConfigRecord = { id:'', module:'Lectio', key:'', value:'', type:'STRING', description:'', active:true, updatedAt:'' };
export function IntegrationsPage(){
  const [items,setItems]=useState<IntegrationConfigRecord[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [mapsStatus,setMapsStatus]=useState<IntegrationStatus|null>(null); const [driveStatus,setDriveStatus]=useState<IntegrationStatus|null>(null);
  const [open,setOpen]=useState(false); const [editing,setEditing]=useState<IntegrationConfigRecord>(empty); const [saving,setSaving]=useState(false);
  const load=async()=>{setLoading(true);setError('');try{setItems((await api.get<IntegrationConfigRecord[]>('/integrations')).data)}catch(e){setError(apiErrorMessage(e))}finally{setLoading(false)}};
  useEffect(()=>{void load(); void api.get<IntegrationStatus>('/maps/status').then(r=>setMapsStatus(r.data)).catch(()=>setMapsStatus({enabled:false,configured:false,message:'Google Maps ainda não configurado.'})); void api.get<IntegrationStatus>('/drive/status').then(r=>setDriveStatus(r.data)).catch(()=>setDriveStatus({enabled:false,configured:false,message:'Google Drive ainda não configurado.'}))},[]);
  const save=async()=>{setSaving(true);setError('');try{await api.patch('/integrations',editing);setOpen(false);await load()}catch(e){setError(apiErrorMessage(e))}finally{setSaving(false)}};
  if(loading)return <Box py={10} textAlign="center"><CircularProgress/></Box>;
  return <Box><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Typography variant="h4">Integrações</Typography><Typography color="text.secondary">Configurações centralizadas na aba Integracoes do Google Sheets.</Typography></Box><Button variant="contained" startIcon={<AddOutlined/>} onClick={()=>{setEditing(empty);setOpen(true)}}>Nova configuração</Button></Stack>
  {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}<Alert severity="info" sx={{mb:2}}>As fontes e regras da Lectio são gravadas aqui. Configurações gerais permanecem em ConfiguracoesSistema.</Alert><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:2,mb:3}}><Card variant="outlined"><CardContent><Stack direction="row" gap={1} alignItems="center"><MapOutlined/><Typography variant="h6">Google Maps</Typography></Stack><Chip sx={{mt:2}} label={mapsStatus?.enabled&&mapsStatus?.configured?'Pronto':'Aguardando configuração'} color={mapsStatus?.enabled&&mapsStatus?.configured?'success':'default'}/><Typography mt={1} color="text.secondary">{mapsStatus?.message||'Verificando configuração...'}</Typography></CardContent></Card><Card variant="outlined"><CardContent><Stack direction="row" gap={1} alignItems="center"><CloudOutlined/><Typography variant="h6">Google Drive</Typography></Stack><Chip sx={{mt:2}} label={driveStatus?.enabled&&driveStatus?.configured?'Pronto':'Aguardando configuração'} color={driveStatus?.enabled&&driveStatus?.configured?'success':'default'}/><Typography mt={1} color="text.secondary">{driveStatus?.message||'Verificando configuração...'}</Typography></CardContent></Card></Box>
  <Stack gap={1}>{items.length===0?<Alert severity="warning">Nenhuma integração cadastrada. Ao salvar as configurações da Lectio, os registros serão criados automaticamente.</Alert>:items.map(item=><Card key={item.id} variant="outlined"><CardContent><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center"><SettingsSuggestOutlined/><Typography fontWeight={800}>{item.module} / {item.key}</Typography><Chip size="small" label={item.active?'Ativa':'Inativa'} color={item.active?'success':'default'}/></Stack><Typography mt={1}>{item.value}</Typography><Typography color="text.secondary" variant="body2">{item.description||item.type}</Typography></Box><Button onClick={()=>{setEditing(item);setOpen(true)}}>Editar</Button></Stack></CardContent></Card>)}</Stack>
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Configuração de integração</DialogTitle><DialogContent><Stack gap={2} mt={1}><TextField label="Módulo" value={editing.module} onChange={e=>setEditing({...editing,module:e.target.value})}/><TextField label="Chave" value={editing.key} onChange={e=>setEditing({...editing,key:e.target.value.toUpperCase()})}/><TextField label="Valor" value={editing.value} onChange={e=>setEditing({...editing,value:e.target.value})}/><TextField select label="Tipo" value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value})}><MenuItem value="STRING">Texto</MenuItem><MenuItem value="NUMBER">Número</MenuItem><MenuItem value="BOOLEAN">Booleano</MenuItem><MenuItem value="SECRET">Segredo</MenuItem></TextField><TextField label="Descrição" value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})} multiline/><FormControlLabel control={<Switch checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/>} label="Configuração ativa"/></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" startIcon={<SaveOutlined/>} disabled={saving||!editing.module||!editing.key} onClick={save}>Salvar</Button></DialogActions></Dialog></Box>
}
