import {AddAlertOutlined,CheckCircleOutline,DeleteOutline,FilterAltOutlined,LaunchOutlined,MarkEmailReadOutlined,NotificationsActiveOutlined,SearchOutlined,SendOutlined,SettingsOutlined} from '@mui/icons-material';
import {Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,FormControlLabel,IconButton,InputAdornment,InputLabel,MenuItem,Pagination,Select,Stack,Switch,TextField,Typography} from '@mui/material';
import {useEffect,useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {useAuth} from '../auth/AuthContext';
import {notifyNotificationsChanged,useNotifications,type NotificationOptions} from '../notifications/notificationStore';
import {api,apiErrorMessage} from '../services/api';
import {dateInputValueSafe,formatDateSafe} from '../utils/date-utils';
const PAGE_SIZE=8;
export function NotificationsPage(){
 const {user}=useAuth(),navigate=useNavigate();const {items,unreadCount,loading,error,markAllAsRead,toggleRead,remove,reload}=useNotifications();
 const [preferencesOpen,setPreferencesOpen]=useState(false),[preferences,setPreferences]=useState({events:true,confirmations:true,justifications:true,memberships:true,leadership:true,birthdays:true,birthdayAdvance:true,app:true,push:false,sendTime:'08:00',firebaseToken:''}),[q,setQ]=useState(''),[type,setType]=useState(''),[origin,setOrigin]=useState(''),[status,setStatus]=useState(''),[date,setDate]=useState(''),[page,setPage]=useState(1),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const [options,setOptions]=useState<NotificationOptions>({members:[],ministries:[],cells:[],cenacles:[],profiles:[]});
 const [form,setForm]=useState({title:'',message:'',type:'INFO',audience:'TODOS',audienceId:'',origin:'Manual',link:'',referenceType:'',referenceId:'',recipientIds:[] as string[]});
 const canSend=user?.profile!=='MEMBER';
 useEffect(()=>{if(canSend)api.get<NotificationOptions>('/notifications/options').then(r=>setOptions(r.data)).catch(()=>undefined);api.get('/notifications/preferences').then(r=>setPreferences(r.data)).catch(()=>undefined)},[canSend]);
 const filtered=useMemo(()=>items.filter(n=>{const text=`${n.title} ${n.message} ${n.origin}`.toLowerCase();return(!q||text.includes(q.toLowerCase()))&&(!type||n.type===type)&&(!origin||n.origin===origin)&&(!status||(status==='READ'?n.read:!n.read))&&(!date||dateInputValueSafe(n.sentAt)===date)}),[items,q,type,origin,status,date]);
 const total=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)),visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);useEffect(()=>setPage(1),[q,type,origin,status,date]);
 const savePreferences=async()=>{setSaving(true);setMessage('');try{await api.patch('/notifications/preferences',preferences);setPreferencesOpen(false);setMessage('Preferências atualizadas com sucesso.');await reload()}catch(e){setMessage(apiErrorMessage(e))}finally{setSaving(false)}};
 const send=async()=>{setSaving(true);setMessage('');try{await api.post('/notifications',form);setOpen(false);setForm({title:'',message:'',type:'INFO',audience:'TODOS',audienceId:'',origin:'Manual',link:'',referenceType:'',referenceId:'',recipientIds:[]});await reload();notifyNotificationsChanged();setMessage('Notificação enviada com sucesso.')}catch(e){setMessage(apiErrorMessage(e))}finally{setSaving(false)}};
 const audienceOptions=form.audience==='MINISTERIO'?options.ministries:form.audience==='CELULA'?options.cells:form.audience==='CENACULO'?options.cenacles:form.audience==='PERFIL'?options.profiles.map(x=>({id:x,name:x})):[];
 return <Box>
  <Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Typography variant="h4">Central de Notificações</Typography><Typography color="text.secondary">Avisos individuais, coletivos e histórico da missão.</Typography></Box><Stack direction="row" gap={1} flexWrap="wrap"><Button variant="outlined" startIcon={<SettingsOutlined/>} onClick={()=>setPreferencesOpen(true)}>Preferências</Button><Button variant="outlined" startIcon={<MarkEmailReadOutlined/>} onClick={()=>void markAllAsRead()} disabled={!unreadCount}>Marcar todas como lidas</Button>{canSend&&<Button variant="contained" startIcon={<AddAlertOutlined/>} onClick={()=>setOpen(true)}>Nova notificação</Button>}</Stack></Stack>
  {message&&<Alert severity={message.includes('sucesso')?'success':'error'} sx={{mb:2}}>{message}</Alert>}{error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
  <Card sx={{mb:2}}><CardContent><Stack direction={{xs:'column',lg:'row'}} gap={1.5}><TextField fullWidth placeholder="Buscar por título, mensagem ou origem" value={q} onChange={e=>setQ(e.target.value)} InputProps={{startAdornment:<InputAdornment position="start"><SearchOutlined/></InputAdornment>}}/><FormControl sx={{minWidth:150}}><InputLabel>Tipo</InputLabel><Select label="Tipo" value={type} onChange={e=>setType(e.target.value)}><MenuItem value="">Todos</MenuItem>{[...new Set(items.map(i=>i.type))].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><FormControl sx={{minWidth:150}}><InputLabel>Origem</InputLabel><Select label="Origem" value={origin} onChange={e=>setOrigin(e.target.value)}><MenuItem value="">Todas</MenuItem>{[...new Set(items.map(i=>i.origin).filter(Boolean))].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><FormControl sx={{minWidth:150}}><InputLabel>Situação</InputLabel><Select label="Situação" value={status} onChange={e=>setStatus(e.target.value)}><MenuItem value="">Todas</MenuItem><MenuItem value="UNREAD">Não lidas</MenuItem><MenuItem value="READ">Lidas</MenuItem></Select></FormControl><TextField type="date" label="Data" InputLabelProps={{shrink:true}} value={date} onChange={e=>setDate(e.target.value)}/><Button startIcon={<FilterAltOutlined/>} onClick={()=>{setQ('');setType('');setOrigin('');setStatus('');setDate('')}}>Limpar</Button></Stack></CardContent></Card>
  <Stack spacing={1.5}>{loading?<Typography>Carregando...</Typography>:visible.map(item=><Card key={item.id} sx={{borderColor:item.read?'divider':'primary.main',opacity:item.read?0.82:1}}><CardContent><Stack direction="row" spacing={2} alignItems="flex-start"><Box sx={{width:46,height:46,borderRadius:'50%',display:'grid',placeItems:'center',bgcolor:item.read?'rgba(255,255,255,.05)':'rgba(155,107,62,.18)',color:item.read?'text.secondary':'primary.main'}}>{item.read?<CheckCircleOutline/>:<NotificationsActiveOutlined/>}</Box><Box flex={1}><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Typography fontWeight={800}>{item.title}</Typography><Chip size="small" label={item.type}/><Chip size="small" variant="outlined" label={item.origin||'Sistema'}/>{!item.read&&<Chip size="small" color="primary" label="Nova"/>}</Stack><Typography color="text.secondary" mt={0.5}>{item.message}</Typography><Typography color="text.secondary" fontSize={12} mt={1}>Enviada por {item.senderName||'Sistema'} • {formatDateSafe(item.sentAt)} • Público: {item.audience}</Typography></Box><Stack direction="row">{item.link&&<IconButton aria-label="Abrir conteúdo" onClick={()=>navigate(item.link)}><LaunchOutlined/></IconButton>}<IconButton aria-label={item.read?'Marcar como não lida':'Marcar como lida'} onClick={()=>void toggleRead(item)}><MarkEmailReadOutlined/></IconButton>{item.canDelete&&<IconButton aria-label="Excluir" onClick={()=>void remove(item.id)}><DeleteOutline/></IconButton>}</Stack></Stack></CardContent></Card>)}</Stack>
  {!loading&&!visible.length&&<Card><CardContent sx={{textAlign:'center',py:8}}><NotificationsActiveOutlined sx={{fontSize:52,color:'text.disabled'}}/><Typography variant="h6">Nenhuma notificação encontrada</Typography></CardContent></Card>}
  <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems="center" mt={2} gap={1}><Typography color="text.secondary">{filtered.length} registro(s) • {unreadCount} não lida(s)</Typography><Pagination count={total} page={Math.min(page,total)} onChange={(_,v)=>setPage(v)}/></Stack>

  <Dialog open={preferencesOpen} onClose={()=>setPreferencesOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Preferências de notificações</DialogTitle><DialogContent><Stack mt={1} spacing={1}><FormControlLabel control={<Switch checked={preferences.events} onChange={e=>setPreferences({...preferences,events:e.target.checked})}/>} label="Eventos e alterações"/><FormControlLabel control={<Switch checked={preferences.confirmations} onChange={e=>setPreferences({...preferences,confirmations:e.target.checked})}/>} label="Confirmações pendentes"/><FormControlLabel control={<Switch checked={preferences.justifications} onChange={e=>setPreferences({...preferences,justifications:e.target.checked})}/>} label="Justificativas"/><FormControlLabel control={<Switch checked={preferences.memberships} onChange={e=>setPreferences({...preferences,memberships:e.target.checked})}/>} label="Novos vínculos"/><FormControlLabel control={<Switch checked={preferences.leadership} onChange={e=>setPreferences({...preferences,leadership:e.target.checked})}/>} label="Mudanças de liderança"/><FormControlLabel control={<Switch checked={preferences.birthdays} onChange={e=>setPreferences({...preferences,birthdays:e.target.checked})}/>} label="Aniversários do dia"/><FormControlLabel control={<Switch checked={preferences.birthdayAdvance} onChange={e=>setPreferences({...preferences,birthdayAdvance:e.target.checked})}/>} label="Lembrete antecipado de aniversário"/><FormControlLabel control={<Switch checked={preferences.app} onChange={e=>setPreferences({...preferences,app:e.target.checked})}/>} label="Notificações no aplicativo"/><FormControlLabel control={<Switch checked={preferences.push} onChange={e=>setPreferences({...preferences,push:e.target.checked})}/>} label="Firebase Push (estrutura preparada)"/><TextField type="time" label="Horário preferido de envio" InputLabelProps={{shrink:true}} value={preferences.sendTime} onChange={e=>setPreferences({...preferences,sendTime:e.target.value})}/></Stack></DialogContent><DialogActions><Button onClick={()=>setPreferencesOpen(false)}>Cancelar</Button><Button variant="contained" disabled={saving} onClick={()=>void savePreferences()}>Salvar</Button></DialogActions></Dialog>
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="md"><DialogTitle>Enviar notificação</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Título" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><TextField label="Mensagem" multiline minRows={4} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><Stack direction={{xs:'column',sm:'row'}} gap={2}><FormControl fullWidth><InputLabel>Tipo</InputLabel><Select label="Tipo" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}>{['INFO','EVENTO','LECTIO','SOMA','MEMBRO','SISTEMA'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><FormControl fullWidth><InputLabel>Público</InputLabel><Select label="Público" value={form.audience} onChange={e=>setForm({...form,audience:e.target.value,audienceId:'',recipientIds:[]})}>{user?.profile==='ADMIN'&&<MenuItem value="TODOS">Todos</MenuItem>}<MenuItem value="INDIVIDUAL">Individual</MenuItem>{user?.profile!=='CELL_LEADER'&&<MenuItem value="MINISTERIO">Ministério</MenuItem>}<MenuItem value="CELULA">Célula</MenuItem>{user?.profile!=='CELL_LEADER'&&<MenuItem value="CENACULO">Cenáculo</MenuItem>}{user?.profile==='ADMIN'&&<MenuItem value="PERFIL">Perfil</MenuItem>}</Select></FormControl></Stack>{form.audience==='INDIVIDUAL'?<FormControl fullWidth><InputLabel>Destinatários</InputLabel><Select multiple label="Destinatários" value={form.recipientIds} onChange={e=>setForm({...form,recipientIds:typeof e.target.value==='string'?e.target.value.split(','):e.target.value})}>{options.members.map(m=><MenuItem key={m.id} value={m.id}>{m.name} — {m.email}</MenuItem>)}</Select></FormControl>:form.audience!=='TODOS'&&<FormControl fullWidth><InputLabel>Destino</InputLabel><Select label="Destino" value={form.audienceId} onChange={e=>setForm({...form,audienceId:e.target.value})}>{audienceOptions.map((o:{id:string;name:string})=><MenuItem key={o.id} value={o.id}>{o.name}</MenuItem>)}</Select></FormControl>}<Stack direction={{xs:'column',sm:'row'}} gap={2}><TextField fullWidth label="Origem" value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}/><TextField fullWidth label="Link interno" placeholder="/eventos/123" value={form.link} onChange={e=>setForm({...form,link:e.target.value})}/></Stack></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" startIcon={<SendOutlined/>} disabled={saving||!form.title.trim()||!form.message.trim()} onClick={()=>void send()}>{saving?'Enviando...':'Enviar'}</Button></DialogActions></Dialog>
 </Box>
}
