import {
  AccountCircleOutlined, ChurchOutlined, EditOutlined, GroupsOutlined,
  Instagram, LocationOnOutlined, NotificationsOutlined, PhotoCameraOutlined,
  SaveOutlined, VolunteerActivismOutlined,
} from '@mui/icons-material';
import {
  Alert, Avatar, Box, Button, Card, CardContent, Chip, CircularProgress, Divider,
  FormControlLabel, IconButton, Stack, Switch, Tab, Tabs, TextField, Typography,
} from '@mui/material';
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { useAuth } from '../auth/AuthContext';
import { api, apiErrorMessage } from '../services/api';
import { FileUploader } from '../components/drive/FileUploader';
import type { Member } from '../types';

type LinkItem={id:string;name:string;role?:string;leader?:string;day?:string;time?:string;recurrence?:string};
type ProfileLeader={structureId:string;structureName:string;name:string};
type ProfilePayload={member:Member;links:{ministries:LinkItem[];cells:LinkItem[];cenacles:LinkItem[];leader:string;leaders?:ProfileLeader[];formator:string}};
type Preferences={events:boolean;confirmations:boolean;justifications:boolean;memberships:boolean;leadership:boolean;birthdays:boolean;birthdayAdvance:boolean;app:boolean;push:boolean;sendTime:string;firebaseToken:string};
const emptyPreferences:Preferences={events:true,confirmations:true,justifications:true,memberships:true,leadership:true,birthdays:true,birthdayAdvance:true,app:true,push:false,sendTime:'08:00',firebaseToken:''};

export function ProfilePage(){
 const {user,refreshSession}=useAuth(); const photoFieldRef=useRef<HTMLInputElement>(null);
 const [tab,setTab]=useState(0); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [payload,setPayload]=useState<ProfilePayload|null>(null);
 const [prefs,setPrefs]=useState<Preferences>(emptyPreferences);
 const [form,setForm]=useState({name:'',email:'',photo:'',phone:'',birthDate:'',city:'',state:'',bio:'',instagram:'',role:'',gifts:'',formator:''});
 const load=async()=>{setLoading(true);setError('');try{const [profile,preferences]=await Promise.all([api.get<ProfilePayload>('/members/me/profile'),api.get<Preferences>('/notifications/preferences')]);setPayload(profile.data);const m=profile.data.member;setForm({name:m.name,email:m.email,photo:m.photo,phone:m.phone,birthDate:m.birthDate||'',city:m.city,state:m.state,bio:m.bio,instagram:m.instagram,role:m.role,gifts:m.gifts.join(', '),formator:m.formator||''});setPrefs(preferences.data);}catch(e){setError(apiErrorMessage(e));}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const initials=useMemo(()=>form.name.split(' ').filter(Boolean).slice(0,2).map(v=>v[0]).join('').toUpperCase(),[form.name]);
 const valid=()=>{if(form.name.trim().length<2)return 'Informe um nome válido.';if(form.phone&&form.phone.replace(/\D/g,'').length<10)return 'Informe um telefone válido com DDD.';if(form.birthDate&&!/^\d{4}-\d{2}-\d{2}$/.test(form.birthDate))return 'Informe uma data de nascimento válida.';if(form.instagram&&form.instagram.length>100)return 'O Instagram deve ter até 100 caracteres.';return ''};
 const saveProfile=async()=>{const message=valid();if(message){setError(message);return}if(!payload)return;setSaving(true);setError('');try{await api.patch('/members/me/profile',{name:form.name,photo:form.photo,phone:form.phone,birthDate:form.birthDate,city:form.city,state:form.state,bio:form.bio,instagram:form.instagram,gifts:form.gifts.split(',').map(v=>v.trim()).filter(Boolean),formator:form.formator});await refreshSession();await load();setSuccess('Perfil atualizado com sucesso.');}catch(e){setError(apiErrorMessage(e));}finally{setSaving(false)}};
 const savePrefs=async()=>{setSaving(true);setError('');try{await api.patch('/notifications/preferences',prefs);setSuccess('Preferências de notificações atualizadas.');}catch(e){setError(apiErrorMessage(e));}finally{setSaving(false)}};
 if(loading)return <Box minHeight={360} display="grid" sx={{placeItems:'center'}}><CircularProgress/></Box>;
 const links=payload?.links;
 return <Box><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2} mb={3}><Box><Typography variant="h4" fontWeight={900}>Perfil pessoal</Typography><Typography color="text.secondary">Seus dados, vínculos e preferências em um só lugar.</Typography></Box><Chip icon={<AccountCircleOutlined/>} label={user?.profile||'MEMBER'} color="primary" variant="outlined"/></Stack>
  {error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}{success&&<Alert severity="success" sx={{mb:2}} onClose={()=>setSuccess('')}>{success}</Alert>}
  <Card sx={{overflow:'hidden'}}><Box sx={{height:120,background:'linear-gradient(120deg, rgba(255,255,255,.08), rgba(255,255,255,.02))'}}/><CardContent sx={{mt:-8,p:{xs:2,md:4}}}><Stack direction={{xs:'column',sm:'row'}} alignItems={{xs:'center',sm:'flex-end'}} spacing={2} mb={3}><Box position="relative"><Avatar src={form.photo} sx={{width:128,height:128,fontSize:38,border:'5px solid',borderColor:'background.paper'}}>{initials}</Avatar><IconButton color="primary" onClick={()=>{setTab(0);setTimeout(()=>photoFieldRef.current?.focus(),50)}} sx={{position:'absolute',right:0,bottom:4,bgcolor:'background.paper',boxShadow:2}}><PhotoCameraOutlined/></IconButton></Box><Box flex={1} textAlign={{xs:'center',sm:'left'}}><Typography variant="h5" fontWeight={900}>{form.name}</Typography><Typography color="primary.main" fontWeight={700}>{form.role||'Membro'}</Typography><Typography color="text.secondary">{form.email}</Typography></Box><Button startIcon={<EditOutlined/>} variant="outlined" onClick={()=>setTab(0)}>Editar perfil</Button></Stack>
   <Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto"><Tab label="Dados pessoais"/><Tab label="Vínculos"/><Tab label="Preferências"/></Tabs><Divider/>
   <Box pt={3}>{tab===0&&<Stack spacing={3}><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:2}}><TextField required label="Nome" value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))}/><TextField label="E-mail" value={form.email} disabled helperText="O e-mail é vinculado ao login Google."/><TextField label="Telefone" value={form.phone} onChange={e=>setForm(v=>({...v,phone:e.target.value}))}/><TextField label="Data de nascimento" type="date" value={form.birthDate} onChange={e=>setForm(v=>({...v,birthDate:e.target.value}))} InputLabelProps={{shrink:true}}/><TextField label="Cidade" value={form.city} onChange={e=>setForm(v=>({...v,city:e.target.value}))}/><TextField label="Estado" value={form.state} onChange={e=>setForm(v=>({...v,state:e.target.value}))}/><TextField label="Instagram" value={form.instagram} onChange={e=>setForm(v=>({...v,instagram:e.target.value}))} InputProps={{startAdornment:<Instagram sx={{mr:1}}/>}}/><TextField label="Formador" value={form.formator} onChange={e=>setForm(v=>({...v,formator:e.target.value}))} helperText="Você pode atualizar este campo quando houver troca de formador."/><TextField label="Função" value={form.role} disabled helperText="Alterada somente pela administração."/><TextField label="Dons" value={form.gifts} onChange={e=>setForm(v=>({...v,gifts:e.target.value}))} helperText="Separe os dons por vírgula." sx={{gridColumn:{md:'1 / -1'}}}/><TextField label="Biografia" value={form.bio} onChange={e=>setForm(v=>({...v,bio:e.target.value}))} multiline minRows={4} inputProps={{maxLength:1000}} helperText={`${form.bio.length}/1000`} sx={{gridColumn:{md:'1 / -1'}}}/></Box><Box><Typography fontWeight={800} mb={1}>Foto do perfil</Typography><Typography color="text.secondary" variant="body2" mb={1.5}>Selecione uma imagem da galeria, câmera ou armazenamento do seu dispositivo.</Typography>{payload?.member?.id&&<FileUploader referenceId={payload.member.id} category="MEMBER_PHOTO" imagesOnly label="Selecionar foto do dispositivo" onUploaded={async(file)=>{setForm(v=>({...v,photo:file.downloadUrl||file.webViewLink}));await refreshSession();await load();setSuccess('Foto do perfil atualizada com sucesso.')}}/>}<TextField inputRef={photoFieldRef} fullWidth sx={{mt:2}} label="URL alternativa da foto" value={form.photo} onChange={e=>setForm(v=>({...v,photo:e.target.value}))} helperText="Também é possível informar uma URL pública de imagem."/></Box><Button variant="contained" startIcon={saving?<CircularProgress size={18}/>:<SaveOutlined/>} disabled={saving} onClick={saveProfile} sx={{alignSelf:'flex-start'}}>Salvar perfil</Button></Stack>}
   {tab===1&&<Stack spacing={3}><Info title="Acompanhamento" icon={<VolunteerActivismOutlined/>} chips={[...(links?.leaders||[]).map(v=>`Líder de ${v.structureName}: ${v.name}`),links?.formator?`Formador: ${links.formator}`:'Formador não informado']}/><Info title="Ministérios" icon={<ChurchOutlined/>} chips={(links?.ministries||[]).map(v=>`${v.name}${v.role?` • ${v.role}`:''}`)} empty="Nenhum ministério vinculado."/><Info title="Célula" icon={<GroupsOutlined/>} chips={(links?.cells||[]).map(v=>`${v.name}${v.day?` • ${v.day}`:''}${v.time?` às ${v.time}`:''}`)} empty="Nenhuma célula vinculada."/><Info title="Cenáculos" icon={<LocationOnOutlined/>} chips={(links?.cenacles||[]).map(v=>`${v.name}${v.recurrence?` • ${v.recurrence}`:''}`)} empty="Nenhum cenáculo vinculado."/></Stack>}
   {tab===2&&<Stack spacing={3}><Alert severity="info">Escolha quais categorias deseja receber. O horário será usado pelas automações futuras.</Alert><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:1}}>{([['events','Eventos'],['confirmations','Confirmações pendentes'],['justifications','Justificativas'],['memberships','Novos vínculos'],['leadership','Mudanças de liderança'],['birthdays','Aniversários'],['birthdayAdvance','Lembrete antecipado de aniversário'],['app','Notificações no aplicativo'],['push','Firebase Push']] as const).map(([key,label])=><FormControlLabel key={key} control={<Switch checked={prefs[key]} onChange={e=>setPrefs(v=>({...v,[key]:e.target.checked}))}/>} label={label}/>)}</Box><TextField label="Horário preferido de envio" type="time" value={prefs.sendTime} onChange={e=>setPrefs(v=>({...v,sendTime:e.target.value}))} InputLabelProps={{shrink:true}} sx={{maxWidth:260}}/><Stack direction="row" spacing={1} alignItems="center"><NotificationsOutlined color="primary"/><Typography color="text.secondary">As preferências são salvas no Google Sheets e aplicadas à Central de Notificações.</Typography></Stack><Button variant="contained" startIcon={saving?<CircularProgress size={18}/>:<SaveOutlined/>} disabled={saving} onClick={savePrefs} sx={{alignSelf:'flex-start'}}>Salvar preferências</Button></Stack>}</Box>
  </CardContent></Card>
 </Box>
}
function Info({title,icon,chips,empty}:{title:string;icon:ReactNode;chips:string[];empty?:string}){return <Card variant="outlined"><CardContent><Stack direction="row" spacing={1} alignItems="center" mb={1.5}>{icon}<Typography variant="h6" fontWeight={800}>{title}</Typography></Stack>{chips.length?<Stack direction="row" gap={1} flexWrap="wrap">{chips.map((v,i)=><Chip key={`${v}-${i}`} label={v}/>)}</Stack>:<Typography color="text.secondary">{empty}</Typography>}</CardContent></Card>}
