import { AddOutlined, DeleteOutline, EditOutlined, RefreshOutlined, SaveOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardContent, Checkbox, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, IconButton, MenuItem, Stack, Switch, Tab, Tabs, TextField, Tooltip, Typography } from '@mui/material';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, apiErrorMessage } from '../services/api';
import { useAuth } from '../auth/AuthContext';

type Profile={id?:string;code:string;name:string;description:string;level:number;active:boolean};
type Perm={id?:string;code:string;resource:string;action:string;description:string;active:boolean};
type Link={id?:string;profileCode:string;permissionCode:string;allowed:boolean;scope:string;active?:boolean};
type Data={profiles:Profile[];permissions:Perm[];profilePermissions:Link[]};
type Form={id?:string;resource:string;action:string;description:string;active:boolean};
const empty:Form={resource:'',action:'',description:'',active:true};
const displayCode=(code:string)=>String(code||'').toLowerCase().replace(':','.').replaceAll('_','-');
const profileLabels:Record<string,{name:string;description:string;level:number}>={DEVELOPER:{name:'Desenvolvedor',description:'Administração técnica total da plataforma.',level:100},MISSION_LEADER:{name:'Líder Missão',description:'Responsável pela administração funcional da missão.',level:90},MINISTRY_LEADER:{name:'Líder de Ministério',description:'Gestão no escopo do ministério.',level:60},CELL_LEADER:{name:'Líder de Célula',description:'Gestão no escopo da célula.',level:40},MEMBER:{name:'Membro',description:'Acesso pessoal e consultas gerais.',level:10}};
const profileView=(p:Profile)=>({name:p.name||profileLabels[p.code]?.name||p.code||'Perfil sem nome',description:p.description||profileLabels[p.code]?.description||'Sem descrição.',level:Number.isFinite(Number(p.level))&&Number(p.level)>0?Number(p.level):(profileLabels[p.code]?.level||0)});

export function RbacPage(){
 const {hasRole}=useAuth(); const canEdit=hasRole('DEVELOPER');
 const [tab,setTab]=useState(2); const [data,setData]=useState<Data|null>(null); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
 const [selectedProfile,setSelectedProfile]=useState(''); const [search,setSearch]=useState(''); const [dialog,setDialog]=useState(false); const [form,setForm]=useState<Form>(empty);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const r=await api.get<Data>('/rbac/catalog');setData(r.data);setSelectedProfile(v=>v||r.data.profiles[0]?.code||'');}catch(e){setError(apiErrorMessage(e));}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const matrix=useMemo(()=>new Map((data?.profilePermissions||[]).map(x=>[`${x.profileCode}|${x.permissionCode}`,x])),[data]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return (data?.permissions||[]).filter(p=>!q||displayCode(p.code).includes(q)||p.description.toLowerCase().includes(q)||p.resource.toLowerCase().includes(q));},[data,search]);
 const toggle=async(permissionCode:string,allowed:boolean)=>{if(!canEdit)return;setSaving(true);setError('');try{const old=matrix.get(`${selectedProfile}|${permissionCode}`);await api.put('/permissions/matrix',{profileCode:selectedProfile,permissionCode,allowed,scope:old?.scope||scopeFor(selectedProfile)});setData(d=>d?{...d,profilePermissions:[...d.profilePermissions.filter(x=>!(x.profileCode===selectedProfile&&x.permissionCode===permissionCode)),{profileCode:selectedProfile,permissionCode,allowed,scope:old?.scope||scopeFor(selectedProfile),active:true}]}:d);}catch(e){setError(apiErrorMessage(e));}finally{setSaving(false);}};
 const changeScope=async(permissionCode:string,scope:string)=>{const old=matrix.get(`${selectedProfile}|${permissionCode}`);await api.put('/permissions/matrix',{profileCode:selectedProfile,permissionCode,allowed:old?.allowed||false,scope});await load();};
 const savePermission=async()=>{setSaving(true);setError('');try{if(form.id)await api.patch(`/permissions/${form.id}`,form);else await api.post('/permissions',form);setDialog(false);setSuccess('Permissão salva com sucesso.');await load();}catch(e){setError(apiErrorMessage(e));}finally{setSaving(false);}};
 const remove=async(p:Perm)=>{if(!p.id||!confirm(`Excluir a permissão ${displayCode(p.code)}? Os vínculos com perfis também serão removidos.`))return;setSaving(true);try{await api.delete(`/permissions/${p.id}`);await load();}catch(e){setError(apiErrorMessage(e));}finally{setSaving(false);}};
 const seed=async()=>{setSaving(true);try{await api.post('/permissions/seed/default');setSuccess('Permissões e matriz padrão restauradas.');await load();}catch(e){setError(apiErrorMessage(e));}finally{setSaving(false);}};
 if(loading&&!data)return <Stack alignItems="center" py={8}><CircularProgress/></Stack>;
 return <Box>
  <Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2} mb={2}><Box><Typography variant="h4" fontWeight={800}>Sistema de permissões</Typography><Typography color="text.secondary">CRUD de permissões e matriz editável de acesso por perfil.</Typography></Box>{canEdit&&<Stack direction="row" gap={1}><Button variant="outlined" startIcon={<RefreshOutlined/>} disabled={saving} onClick={()=>void seed()}>Restaurar padrões</Button><Button variant="contained" startIcon={<AddOutlined/>} onClick={()=>{setForm(empty);setDialog(true)}}>Criar permissão</Button></Stack>}</Stack>
  {error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}{success&&<Alert severity="success" sx={{mb:2}} onClose={()=>setSuccess('')}>{success}</Alert>}
  <Tabs value={tab} onChange={(_,v)=>setTab(v)} sx={{mb:2}}><Tab label={`Perfis (${data?.profiles.length||0})`}/><Tab label={`Permissões (${data?.permissions.length||0})`}/><Tab label="Matriz de acesso"/></Tabs>
  {tab===0&&<Stack spacing={1.5}>{data?.profiles.map(x=>{const view=profileView(x);return <Card key={x.id||x.code} variant="outlined"><CardContent><Stack direction={{xs:'column',sm:'row'}} gap={1} alignItems={{sm:'center'}} flexWrap="wrap"><Typography fontWeight={800} variant="h6">{view.name}</Typography><Chip size="small" label={x.code||'SEM_CODIGO'}/><Chip size="small" label={`Nível ${view.level}`}/><Chip size="small" color={x.active?'success':'default'} label={x.active?'Ativo':'Inativo'}/></Stack><Typography color="text.secondary" mt={1}>{view.description}</Typography></CardContent></Card>})}</Stack>}
  {tab===1&&<><TextField fullWidth size="small" label="Buscar permissão" value={search} onChange={e=>setSearch(e.target.value)} sx={{mb:2}}/><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'repeat(2,1fr)'},gap:1.5}}>{filtered.map(p=><Card key={p.code} variant="outlined"><CardContent><Stack direction="row" justifyContent="space-between" gap={1}><Box><Typography fontWeight={800}>{displayCode(p.code)}</Typography><Typography variant="body2" color="text.secondary">{p.description}</Typography><Stack direction="row" gap={1} mt={1}><Chip size="small" label={p.resource}/><Chip size="small" label={p.action}/><Chip size="small" color={p.active?'success':'default'} label={p.active?'Ativa':'Inativa'}/></Stack></Box>{canEdit&&<Stack direction="row"><Tooltip title="Editar"><IconButton onClick={()=>{setForm({id:p.id,resource:p.resource,action:p.action,description:p.description,active:p.active});setDialog(true)}}><EditOutlined/></IconButton></Tooltip><Tooltip title="Excluir"><IconButton color="error" onClick={()=>void remove(p)}><DeleteOutline/></IconButton></Tooltip></Stack>}</Stack></CardContent></Card>)}</Box></>}
  {tab===2&&<Card variant="outlined"><CardContent><Stack direction={{xs:'column',md:'row'}} gap={2} justifyContent="space-between" mb={2}><TextField select label="Perfil" value={selectedProfile} onChange={e=>setSelectedProfile(e.target.value)} sx={{minWidth:260}}>{data?.profiles.filter(p=>p.active&&p.code).map(p=>{const view=profileView(p);return <MenuItem key={p.code} value={p.code}>{view.name} — Nível {view.level}</MenuItem>})}</TextField><TextField size="small" label="Buscar permissão" value={search} onChange={e=>setSearch(e.target.value)} sx={{minWidth:{md:320}}}/></Stack><Box sx={{overflowX:'auto'}}><Box sx={{minWidth:720}}>{filtered.map((p,i)=>{const link=matrix.get(`${selectedProfile}|${p.code}`);return <Stack key={p.code} direction="row" alignItems="center" sx={{py:1.1,borderTop:i?'1px solid':'none',borderColor:'divider'}}><Box sx={{flex:1}}><Typography fontWeight={700}>{displayCode(p.code)}</Typography><Typography variant="caption" color="text.secondary">{p.description}</Typography></Box><TextField select size="small" value={link?.scope||scopeFor(selectedProfile)} disabled={!canEdit||saving} onChange={e=>void changeScope(p.code,e.target.value)} sx={{width:140,mr:2}}><MenuItem value="OWN">Próprio</MenuItem><MenuItem value="CELL">Célula</MenuItem><MenuItem value="MINISTRY">Ministério</MenuItem><MenuItem value="MISSION">Missão</MenuItem><MenuItem value="ALL">Todos</MenuItem></TextField><FormControlLabel control={<Checkbox checked={Boolean(link?.allowed)} disabled={!canEdit||saving||!p.active} onChange={e=>void toggle(p.code,e.target.checked)}/>} label={link?.allowed?'Permitido':'Negado'}/></Stack>})}</Box></Box>{!canEdit&&<Alert severity="info" sx={{mt:2}}>Somente o perfil Desenvolvedor pode editar a matriz.</Alert>}</CardContent></Card>}
  <Dialog open={dialog} onClose={()=>!saving&&setDialog(false)} fullWidth maxWidth="sm"><DialogTitle>{form.id?'Editar permissão':'Criar permissão'}</DialogTitle><DialogContent><Stack gap={2} mt={1}><TextField required label="Recurso" placeholder="members" value={form.resource} onChange={e=>setForm({...form,resource:e.target.value})}/><TextField required label="Ação" placeholder="read" value={form.action} onChange={e=>setForm({...form,action:e.target.value})}/><TextField label="Descrição" multiline minRows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><FormControlLabel control={<Switch checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>} label="Permissão ativa"/><Alert severity="info">Código gerado: {displayCode(`${form.resource||'resource'}:${form.action||'action'}`)}</Alert></Stack></DialogContent><DialogActions><Button onClick={()=>setDialog(false)}>Cancelar</Button><Button variant="contained" startIcon={<SaveOutlined/>} disabled={saving||!form.resource.trim()||!form.action.trim()} onClick={()=>void savePermission()}>Salvar</Button></DialogActions></Dialog>
 </Box>;
}
function scopeFor(profile:string){if(profile==='DEVELOPER'||profile==='MISSION_LEADER')return 'ALL';if(profile==='MINISTRY_LEADER')return 'MINISTRY';if(profile==='CELL_LEADER')return 'CELL';return 'OWN';}
