import { AssessmentOutlined, DownloadOutlined, PrintOutlined, WarningAmberOutlined } from '@mui/icons-material';
import { Alert, Avatar, Box, Button, Card, CardContent, Chip, CircularProgress, FormControl, InputLabel, MenuItem, Pagination, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useEffect, useMemo, useState } from 'react';
import { api, apiErrorMessage } from '../services/api';

type Option={id:string;name:string}; type Options={members:Option[];ministries:Option[];cells:Option[];cenacles:Option[]};
type Member={id:string;name:string;email:string;photo:string;birthDate:string;profile:string;ministryNames:string[];cellNames:string[];cenacleNames:string[];presences:number;absences:number;justifiedAbsences:number;attendanceRate:number;eventConfirmed:number;eventAbsent:number;participationScore:number};
type Report={generatedAt:string;indicators:{records:number;presences:number;absences:number;rate:number;members:number;eventConfirmations:number;eventAbsences:number;birthdays:number};comparison:{current:{rate:number};previous:{rate:number};rateDifference:number};monthly:{month:string;presences:number;absences:number;rate:number}[];birthdays:{id:string;name:string;birthDate:string;photo:string}[];ranking:Member[];lowFrequency:Member[];members:Member[];pagination:{page:number;pageSize:number;total:number;totalPages:number}};
type History={id:string;formato:string;arquivo_nome:string;total_registros:string;gerado_por_nome:string;criado_em:string};
const now=new Date(); const iso=(d:Date)=>d.toISOString().slice(0,10); const start=iso(new Date(now.getFullYear(),now.getMonth(),1)); const end=iso(now); const prevEnd=iso(new Date(now.getFullYear(),now.getMonth(),0)); const prevStart=iso(new Date(now.getFullYear(),now.getMonth()-1,1));

function MiniChart({data}:{data:Report['monthly']}){const max=Math.max(1,...data.map(x=>x.presences+x.absences));return <Box display="flex" alignItems="end" gap={1} height={180}>{data.map(x=><Box key={x.month} flex={1} textAlign="center"><Box display="flex" alignItems="end" justifyContent="center" gap={0.5} height={130}><Box title={`Presenças: ${x.presences}`} sx={{width:18,height:`${x.presences/max*120}px`,bgcolor:'success.main',borderRadius:'4px 4px 0 0'}}/><Box title={`Faltas: ${x.absences}`} sx={{width:18,height:`${x.absences/max*120}px`,bgcolor:'error.main',borderRadius:'4px 4px 0 0'}}/></Box><Typography variant="caption">{x.month}</Typography><Typography variant="caption" display="block" fontWeight={700}>{x.rate}%</Typography></Box>)}</Box>}

export function ReportsPage({embedded=false}:{embedded?:boolean}){
 const [options,setOptions]=useState<Options>({members:[],ministries:[],cells:[],cenacles:[]}); const [report,setReport]=useState<Report|null>(null); const [history,setHistory]=useState<History[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [filters,setFilters]=useState({startDate:start,endDate:end,compareStartDate:prevStart,compareEndDate:prevEnd,memberId:'',structureType:'ALL',structureId:'',search:'',page:1,pageSize:10,lowFrequencyThreshold:75});
 useEffect(()=>{api.get('/reports/options').then(r=>setOptions(r.data));api.get('/reports/history').then(r=>setHistory(r.data)).catch(()=>undefined)},[]);
 useEffect(()=>{const t=setTimeout(()=>{setLoading(true);api.get('/reports/advanced',{params:filters}).then(r=>setReport(r.data)).catch(e=>setError(apiErrorMessage(e))).finally(()=>setLoading(false))},250);return()=>clearTimeout(t)},[filters]);
 const structures=useMemo(()=>filters.structureType==='MINISTRY'?options.ministries:filters.structureType==='CELL'?options.cells:filters.structureType==='CENACLE'?options.cenacles:[],[filters.structureType,options]);
 const set=<K extends keyof typeof filters>(key:K,value:(typeof filters)[K])=>setFilters(f=>({...f,[key]:value,page:key==='page'?Number(value):1}));
 const exportFile=async(format:'pdf'|'xlsx'|'csv')=>{const r=await api.get('/reports/export',{params:{...filters,format},responseType:'blob'});const url=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=url;a.download=`relatorio.${format==='xlsx'?'xls':format}`;a.click();URL.revokeObjectURL(url);api.get('/reports/history').then(x=>setHistory(x.data));};
 return <Box>{!embedded&&<Typography variant="h4">Relatórios Avançados</Typography>}<Typography color="text.secondary" mb={2}>Assiduidade, eventos, aniversários, comparativos, ranking e exportações.</Typography>
 <Card><CardContent><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(4,1fr)'},gap:2}}><TextField size="small" type="date" label="Início" value={filters.startDate} onChange={e=>set('startDate',e.target.value)} InputLabelProps={{shrink:true}}/><TextField size="small" type="date" label="Fim" value={filters.endDate} onChange={e=>set('endDate',e.target.value)} InputLabelProps={{shrink:true}}/><TextField size="small" type="date" label="Comparar início" value={filters.compareStartDate} onChange={e=>set('compareStartDate',e.target.value)} InputLabelProps={{shrink:true}}/><TextField size="small" type="date" label="Comparar fim" value={filters.compareEndDate} onChange={e=>set('compareEndDate',e.target.value)} InputLabelProps={{shrink:true}}/><FormControl size="small"><InputLabel>Membro</InputLabel><Select label="Membro" value={filters.memberId} onChange={e=>set('memberId',e.target.value)}><MenuItem value="">Todos</MenuItem>{options.members.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select></FormControl><FormControl size="small"><InputLabel>Estrutura</InputLabel><Select label="Estrutura" value={filters.structureType} onChange={e=>{setFilters(f=>({...f,structureType:e.target.value,structureId:'',page:1}))}}><MenuItem value="ALL">Todas</MenuItem><MenuItem value="MINISTRY">Ministério</MenuItem><MenuItem value="CELL">Célula</MenuItem><MenuItem value="CENACLE">Cenáculo</MenuItem></Select></FormControl><FormControl size="small"><InputLabel>Selecionar</InputLabel><Select label="Selecionar" value={filters.structureId} onChange={e=>set('structureId',e.target.value)}><MenuItem value="">Todos</MenuItem>{structures.map(x=><MenuItem key={x.id} value={x.id}>{x.name}</MenuItem>)}</Select></FormControl><TextField size="small" label="Buscar" value={filters.search} onChange={e=>set('search',e.target.value)}/></Box><Stack direction="row" spacing={1} mt={2} flexWrap="wrap"><Button startIcon={<DownloadOutlined/>} onClick={()=>exportFile('pdf')}>PDF</Button><Button startIcon={<DownloadOutlined/>} onClick={()=>exportFile('xlsx')}>Excel</Button><Button startIcon={<DownloadOutlined/>} onClick={()=>exportFile('csv')}>CSV</Button><Button startIcon={<PrintOutlined/>} onClick={()=>window.print()}>Imprimir</Button></Stack></CardContent></Card>
 {error&&<Alert severity="error" sx={{mt:2}}>{error}</Alert>}{loading&&!report?<Box p={8} textAlign="center"><CircularProgress/></Box>:report&&<><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr 1fr',md:'repeat(6,1fr)'},gap:2,mt:2}}>{[['Assiduidade',`${report.indicators.rate}%`],['Evolução',`${report.comparison.rateDifference>=0?'+':''}${report.comparison.rateDifference} p.p.`],['Presenças',report.indicators.presences],['Faltas',report.indicators.absences],['Eventos confirmados',report.indicators.eventConfirmations],['Aniversários',report.indicators.birthdays]].map(([l,v])=><Card key={String(l)}><CardContent><AssessmentOutlined color="primary"/><Typography variant="caption" display="block">{l}</Typography><Typography variant="h5" fontWeight={800}>{v}</Typography></CardContent></Card>)}</Box>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'2fr 1fr'},gap:2,mt:2}}><Card><CardContent><Typography variant="h6">Evolução mensal de presença</Typography><MiniChart data={report.monthly}/></CardContent></Card><Card><CardContent><Typography variant="h6">Alertas de baixa frequência</Typography>{report.lowFrequency.slice(0,8).map(m=><Stack key={m.id} direction="row" justifyContent="space-between" py={1}><Typography variant="body2">{m.name}</Typography><Chip icon={<WarningAmberOutlined/>} size="small" color="warning" label={`${m.attendanceRate}%`}/></Stack>)}{!report.lowFrequency.length&&<Typography color="text.secondary">Nenhum alerta.</Typography>}</CardContent></Card></Box>
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1fr 1fr'},gap:2,mt:2}}><Card><CardContent><Typography variant="h6">Ranking de participação</Typography>{report.ranking.slice(0,10).map((m,i)=><Stack key={m.id} direction="row" justifyContent="space-between" py={1}><Typography>{i+1}. {m.name}</Typography><Chip size="small" label={`${m.participationScore} pts`}/></Stack>)}</CardContent></Card><Card><CardContent><Typography variant="h6">Aniversariantes no período</Typography>{report.birthdays.map(b=><Stack key={b.id} direction="row" spacing={1} alignItems="center" py={1}><Avatar src={b.photo}/><Box><Typography>{b.name}</Typography><Typography variant="caption">{b.birthDate}</Typography></Box></Stack>)}{!report.birthdays.length&&<Typography color="text.secondary">Nenhum aniversariante.</Typography>}</CardContent></Card></Box>
 <Card sx={{mt:2}}><CardContent><Typography variant="h6">Relatório detalhado</Typography><TableContainer><Table size="small"><TableHead><TableRow><TableCell>Membro</TableCell><TableCell>Estrutura</TableCell><TableCell>Presenças</TableCell><TableCell>Faltas</TableCell><TableCell>Assiduidade</TableCell><TableCell>Eventos</TableCell></TableRow></TableHead><TableBody>{report.members.map(m=><TableRow key={m.id}><TableCell>{m.name}</TableCell><TableCell>{[...m.ministryNames,...m.cellNames,...m.cenacleNames].join(', ')||'Sem vínculo'}</TableCell><TableCell>{m.presences}</TableCell><TableCell>{m.absences}</TableCell><TableCell><Chip size="small" label={`${m.attendanceRate}%`} color={m.attendanceRate<75?'warning':'success'}/></TableCell><TableCell>{m.eventConfirmed}</TableCell></TableRow>)}</TableBody></Table></TableContainer><Stack alignItems="center" mt={2}><Pagination count={report.pagination.totalPages} page={report.pagination.page} onChange={(_,v)=>set('page',v)}/></Stack></CardContent></Card>
 <Card sx={{mt:2}}><CardContent><Typography variant="h6">Histórico de relatórios gerados</Typography>{history.slice(0,10).map(h=><Stack key={h.id} direction={{xs:'column',sm:'row'}} justifyContent="space-between" py={1} borderBottom="1px solid" borderColor="divider"><Typography>{h.arquivo_nome}</Typography><Typography variant="caption">{h.formato} · {h.total_registros} registros · {new Date(h.criado_em).toLocaleString('pt-BR')}</Typography></Stack>)}{!history.length&&<Typography color="text.secondary">Nenhuma exportação registrada.</Typography>}</CardContent></Card></>}</Box>
}
