import { AccountBalanceOutlined, ContentCopyOutlined, CreditCardOutlined, FavoriteOutlined, PixOutlined, SettingsOutlined, UploadFileOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardContent, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { DrivePage } from './DrivePage';
import { ReportsPage } from './ReportsPage';
import { FinancialEnterprisePanel } from './FinancialEnterprisePanel';
import { api } from '../services/api';
import { useAuth } from '../auth/AuthContext';

type Settings={campaignName:string;description:string;pixKey:string;pixKeyType:string;beneficiary:string;goal:number;active:boolean;pixBank:string;pixAgency:string;pixAccount:string;pixCnpj:string;subscriptionUrl:string;pixQrCodeUrl:string};
type Subscription={status:'ACTIVE'|'INACTIVE'|'PENDING';plan:string;amount:number|null;nextCharge:string|null;cardLastFour:string|null;manageUrl:string};
type Contribution={id:string;memberName:string;amount:number;date:string;status:string;method:string};
type Payment={id:string;payment_id:string;member_name:string;payer_email:string;status:string;amount:number;payment_method:string;date_created:string;date_approved:string;description:string};
const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);

function SomaContributionPanel({showRecent=true,canAdmin=false}:{showRecent?:boolean;canAdmin?:boolean}){
 const [settings,setSettings]=useState<Settings|null>(null); const [subscription,setSubscription]=useState<Subscription|null>(null); const [items,setItems]=useState<Contribution[]>([]); const [payments,setPayments]=useState<Payment[]>([]);
 const [open,setOpen]=useState(false); const [adminOpen,setAdminOpen]=useState(false); const [saved,setSaved]=useState(false); const [message,setMessage]=useState('');
 const [form,setForm]=useState({memberName:'',email:'',amount:'',notes:''}); const [edit,setEdit]=useState<Settings|null>(null);
 const load=()=>Promise.all([api.get('/soma/settings'),api.get('/soma/subscription/current'),api.get('/soma/payments/my')]).then(([a,b,c])=>{setSettings(a.data);setEdit(a.data);setSubscription(b.data);setPayments(Array.isArray(c.data)?c.data:[])}).catch(console.error);
 useEffect(()=>{load();if(showRecent)api.get('/soma/contributions').then(r=>setItems(Array.isArray(r.data)?r.data:[])).catch(console.error)},[showRecent]);
 const copy=async(text:string,label:string)=>{await navigator.clipboard.writeText(text);setMessage(`${label} copiado.`)};
 const ted=settings?`Banco: ${settings.pixBank}\nAgência: ${settings.pixAgency}\nConta: ${settings.pixAccount}\nCNPJ: ${settings.pixCnpj}`:'';
 const submit=async()=>{await api.post('/soma/contributions',{...form,amount:Number(form.amount),method:'PIX'});setSaved(true);setOpen(false);if(showRecent){const r=await api.get('/soma/contributions');setItems(Array.isArray(r.data)?r.data:[])}};
 const saveSettings=async()=>{if(!edit)return;const r=await api.patch('/soma/settings',edit);setSettings(r.data);setEdit(r.data);setAdminOpen(false);setMessage('Configurações financeiras atualizadas.')};
 if(!settings||!subscription) return <Box minHeight={400} display="grid" sx={{placeItems:'center'}}><CircularProgress/></Box>;
 return <Box>
  <Card sx={{mb:2,background:'linear-gradient(135deg,rgba(25,118,210,.16),rgba(156,39,176,.10))'}}><CardContent sx={{p:{xs:3,md:4}}}><Typography variant="h4" fontWeight={900}>💙 Soma+</Typography><Typography variant="h6" mt={1}>“Cada um contribua segundo propôs em seu coração.”</Typography><Typography color="text.secondary" mt={1}>{settings.description}</Typography></CardContent></Card>
  {message&&<Alert severity="success" sx={{mb:2}} onClose={()=>setMessage('')}>{message}</Alert>}
  {saved&&<Alert severity="success" sx={{mb:2}} onClose={()=>setSaved(false)}>Contribuição registrada. A confirmação será feita pela administração.</Alert>}
  <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1fr 1fr'},gap:2}}>
   <Card><CardContent sx={{p:3}}><CreditCardOutlined color="primary" sx={{fontSize:42}}/><Typography variant="h5" fontWeight={800} mt={1}>Contribuição mensal</Typography><Typography color="text.secondary" my={1.5}>Cadastre o cartão diretamente no ambiente seguro do Mercado Pago. A renovação será automática.</Typography><Button fullWidth size="large" variant="contained" startIcon={<FavoriteOutlined/>} href={settings.subscriptionUrl} target="_blank" rel="noopener noreferrer">Assinar mensalmente</Button></CardContent></Card>
   <Card><CardContent sx={{p:3}}><Typography variant="h5" fontWeight={800}>Minha assinatura</Typography><Stack spacing={1.3} mt={2}><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Status</Typography><Chip size="small" color={subscription.status==='ACTIVE'?'success':'default'} label={subscription.status==='ACTIVE'?'Ativa':'Não vinculada'}/></Stack><Divider/><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Plano</Typography><Typography fontWeight={700}>{subscription.plan}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Valor</Typography><Typography fontWeight={700}>{subscription.amount===null?'Definido no Mercado Pago':money(subscription.amount)}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Próxima cobrança</Typography><Typography fontWeight={700}>{subscription.nextCharge?new Date(subscription.nextCharge).toLocaleDateString('pt-BR'):'Disponível após integração da assinatura'}</Typography></Stack><Stack direction="row" justifyContent="space-between"><Typography color="text.secondary">Cartão</Typography><Typography fontWeight={700}>{subscription.cardLastFour?`•••• ${subscription.cardLastFour}`:'Gerenciado pelo Mercado Pago'}</Typography></Stack><Button variant="outlined" href={subscription.manageUrl} target="_blank" rel="noopener noreferrer">Gerenciar assinatura</Button></Stack></CardContent></Card>
   <Card><CardContent sx={{p:{xs:2,sm:2.5}}}><Stack direction="row" alignItems="center" spacing={1}><PixOutlined color="primary"/><Typography variant="h6" fontWeight={800}>Contribuição via PIX</Typography></Stack><Box component="img" src={settings.pixQrCodeUrl} alt="QR Code Pix" sx={{display:'block',width:'100%',maxWidth:210,aspectRatio:'1 / 1',objectFit:'contain',mx:'auto',my:1.5,borderRadius:1}}/><Box sx={{p:1.25,border:'1px dashed',borderColor:'primary.main',borderRadius:1.5,wordBreak:'break-all'}}><Typography fontSize={11} color="text.secondary">Chave PIX ({settings.pixKeyType})</Typography><Typography fontSize={14} fontWeight={800}>{settings.pixKey}</Typography></Box><Stack direction={{xs:'column',sm:'row'}} spacing={1} mt={1.5}><Button size="small" fullWidth variant="outlined" startIcon={<ContentCopyOutlined/>} onClick={()=>copy(settings.pixKey,'Chave PIX')}>Copiar chave</Button><Button size="small" fullWidth variant="contained" startIcon={<UploadFileOutlined/>} onClick={()=>setOpen(true)}>Registrar</Button></Stack></CardContent></Card>
   <Card><CardContent sx={{p:{xs:2,sm:2.5}}}><Stack direction="row" alignItems="center" spacing={1}><AccountBalanceOutlined color="primary"/><Typography variant="h6" fontWeight={800}>Dados para TED</Typography></Stack><Stack spacing={0.65} mt={1.5}><Info label="Banco" value={settings.pixBank}/><Info label="Agência" value={settings.pixAgency}/><Info label="Conta" value={settings.pixAccount}/><Info label="CNPJ" value={settings.pixCnpj}/></Stack><Button fullWidth size="small" sx={{mt:1.5}} variant="outlined" startIcon={<ContentCopyOutlined/>} onClick={()=>copy(ted,'Dados bancários')}>Copiar dados</Button></CardContent></Card>
  </Box>
  {payments.length>0&&<Card sx={{mt:2}}><CardContent><Typography variant="h6" fontWeight={800} mb={1.5}>Meus pagamentos confirmados</Typography><Box sx={{overflowX:'auto'}}><Box component="table" sx={{width:'100%',borderCollapse:'collapse','th,td':{p:1.2,borderBottom:'1px solid',borderColor:'divider',textAlign:'left',whiteSpace:'nowrap'}}}><thead><tr><th>Data</th><th>Descrição</th><th>Valor</th><th>Forma</th><th>Status</th></tr></thead><tbody>{payments.map(payment=><tr key={payment.payment_id||payment.id}><td>{new Date(payment.date_approved||payment.date_created).toLocaleDateString('pt-BR')}</td><td>{payment.description||'Contribuição Soma+'}</td><td>{money(Number(payment.amount))}</td><td>{payment.payment_method||'Mercado Pago'}</td><td><Chip size="small" color={payment.status==='approved'?'success':'default'} label={payment.status==='approved'?'Aprovado':payment.status}/></td></tr>)}</tbody></Box></Box></CardContent></Card>}
  {canAdmin&&<Card sx={{mt:2}}><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}} spacing={2}><Box><Typography variant="h6" fontWeight={800}>Administração financeira</Typography><Typography color="text.secondary">Altere Pix, TED, QR Code e o link recorrente. Os dados são salvos na aba Financeiro.</Typography></Box><Button startIcon={<SettingsOutlined/>} variant="outlined" onClick={()=>setAdminOpen(true)}>Configurar</Button></Stack></CardContent></Card>}
  {showRecent&&<Card sx={{mt:2}}><CardContent><Typography variant="h6" mb={2}>Contribuições recentes</Typography><Box sx={{overflowX:'auto'}}><Box component="table" sx={{width:'100%',borderCollapse:'collapse','th,td':{p:1.5,borderBottom:'1px solid',borderColor:'divider',textAlign:'left'}}}><thead><tr><th>Data</th><th>Nome</th><th>Valor</th><th>Forma</th><th>Status</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{new Date(i.date+'T12:00:00').toLocaleDateString('pt-BR')}</td><td>{i.memberName}</td><td>{money(i.amount)}</td><td>{i.method}</td><td>{i.status==='CONFIRMED'?'Confirmada':i.status==='PENDING'?'Pendente':'Cancelada'}</td></tr>)}</tbody></Box></Box></CardContent></Card>}
  <Dialog open={open} onClose={()=>setOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Registrar contribuição</DialogTitle><DialogContent><Stack spacing={2} mt={1}><TextField label="Nome" value={form.memberName} onChange={e=>setForm({...form,memberName:e.target.value})}/><TextField label="E-mail" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><TextField label="Valor" type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><TextField select label="Forma" value="PIX"><MenuItem value="PIX">PIX</MenuItem></TextField><TextField label="Observações" multiline rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><Button component="label" variant="outlined" startIcon={<UploadFileOutlined/>}>Selecionar comprovante<input hidden type="file" accept="image/*,.pdf"/></Button></Stack></DialogContent><DialogActions><Button onClick={()=>setOpen(false)}>Cancelar</Button><Button variant="contained" disabled={!form.memberName||Number(form.amount)<=0} onClick={submit}>Enviar registro</Button></DialogActions></Dialog>
  <Dialog open={adminOpen} onClose={()=>setAdminOpen(false)} fullWidth maxWidth="sm"><DialogTitle>Configurações financeiras</DialogTitle><DialogContent>{edit&&<Stack spacing={2} mt={1}><TextField label="Chave PIX" value={edit.pixKey} onChange={e=>setEdit({...edit,pixKey:e.target.value})}/><TextField label="Banco" value={edit.pixBank} onChange={e=>setEdit({...edit,pixBank:e.target.value})}/><TextField label="Agência" value={edit.pixAgency} onChange={e=>setEdit({...edit,pixAgency:e.target.value})}/><TextField label="Conta" value={edit.pixAccount} onChange={e=>setEdit({...edit,pixAccount:e.target.value})}/><TextField label="CNPJ" value={edit.pixCnpj} onChange={e=>setEdit({...edit,pixCnpj:e.target.value})}/><TextField label="Link de assinatura Mercado Pago" value={edit.subscriptionUrl} onChange={e=>setEdit({...edit,subscriptionUrl:e.target.value})}/><TextField label="URL do QR Code" value={edit.pixQrCodeUrl} onChange={e=>setEdit({...edit,pixQrCodeUrl:e.target.value})}/></Stack>}</DialogContent><DialogActions><Button onClick={()=>setAdminOpen(false)}>Cancelar</Button><Button variant="contained" onClick={saveSettings}>Salvar</Button></DialogActions></Dialog>
 </Box>
}
function Info({label,value}:{label:string;value:string}){return <Stack direction="row" justifyContent="space-between" gap={2}><Typography color="text.secondary">{label}</Typography><Typography fontWeight={800} textAlign="right">{value}</Typography></Stack>}

export function SomaPage(){
 const {hasRole}=useAuth(); const isCommonMember=hasRole('MEMBER')&&!hasRole('ADMIN','DEVELOPER','MISSION_LEADER','MINISTRY_LEADER','CELL_LEADER');
 const canViewReports=hasRole('ADMIN','DEVELOPER','MINISTRY_LEADER'); const canAdmin=hasRole('ADMIN','DEVELOPER','MISSION_LEADER');
 const [params,setParams]=useSearchParams(); const values=canViewReports?['contribuicoes','financeiro','relatorios','drive']:['contribuicoes','financeiro','drive']; const requested=params.get('tab')||'contribuicoes'; const current=Math.max(0,values.indexOf(requested)); const setTab=(index:number)=>setParams(index===0?{}:{tab:values[index]});
 return <Box><Typography variant="h4">Soma+</Typography><Typography color="text.secondary" mb={2}>Contribuições recorrentes e avulsas em um só lugar.</Typography><Paper sx={{mb:3}}><Tabs value={current} onChange={(_,value)=>setTab(value)} variant="scrollable"><Tab label="Contribuições e PIX"/><Tab label={canViewReports?"Centro Financeiro":"Minhas Contribuições"}/>{canViewReports&&<Tab label="Relatórios"/>}<Tab label="Google Drive"/></Tabs></Paper>{values[current]==='contribuicoes'?<SomaContributionPanel showRecent={!isCommonMember} canAdmin={canAdmin}/>:values[current]==='financeiro'?<FinancialEnterprisePanel admin={canViewReports}/>:values[current]==='relatorios'?<ReportsPage embedded/>:<DrivePage embedded/>}</Box>
}
